import type { Metadata } from "next";
import type { ReactNode } from "react";
import { ButtonLink, Container, Section } from "../../ui";
import { PdfWorkflowEngine } from "./workflow-engine";
import { VerifyClientSide, LOCAL_ONLY_SLUGS } from "./VerifyClientSide";
// zh-Hant copy is derived from zh via OpenCC (Simplified->Traditional).
import { toHant as ccTpl, deepHant as deepHantTpl } from "./zh-hant";
// Real per-tool-page git dates (datePublished/dateModified) for schema freshness.
// Generated by apps/dockdocs/scripts/gen-tool-dates.mjs from git history (honest,
// per-file, never fabricated). A slug absent here simply gets no dates (OMITTED).
import toolDatesRaw from "./_tool-dates.json";

const toolDates = toolDatesRaw as Record<
  string,
  { datePublished?: string; dateModified?: string }
>;

export type PdfToolItem = {
  title: string;
  description: string;
};

export type PdfToolFaq = {
  question: string;
  answer: string;
};

export type PdfToolCta = {
  eyebrow: string;
  title: string;
  description: string;
  buttonLabel: string;
};

export type PdfToolUpload = {
  title: string;
  description: string;
  buttonLabel: string;
  multiple?: boolean;
  note?: string;
  accept?: string;
  fileBadge?: string;
};

export type PdfToolPageConfig = {
  slug: string;
  locale?: "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko" | "zh-Hant";
  canonicalPath?: string;
  alternateLanguages?: Record<string, string>;
  title: string;
  description: string;
  keywords: string[];
  appName: string;
  schemaName: string;
  breadcrumbName: string;
  heroTitle: string;
  heroDescription: string;
  primaryActionLabel: string;
  stats: Array<[string, string]>;
  upload: PdfToolUpload;
  benefits: PdfToolItem[];
  benefitsTitle: string;
  benefitsDescription: string;
  features: PdfToolItem[];
  featuresTitle: string;
  featuresDescription: string;
  workflowTitle: string;
  workflowDescription: string;
  steps: string[];
  faq: PdfToolFaq[];
  faqTitle: string;
  cta: PdfToolCta;
  relatedTools?: ReactNode | false;
};

type WorkflowState = {
  status: string;
  title: string;
  description: string;
  preview?: ReactNode;
  actionLabel?: string;
  secondaryActionLabel?: string;
};

type IndexingLink = {
  label: string;
  href: string;
  description: string;
};

const siteUrl = "https://dockdocs.app";

const pdfTools = {
  en: [
  {
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    href: "/jpg-to-pdf",
    description: "Turn images, photos, and scans into a PDF document.",
  },
  {
    name: "Compress PDF",
    slug: "compress-pdf",
    href: "/compress-pdf",
    description: "Reduce PDF size for email, portals, and sharing.",
  },
  {
    name: "Merge PDF",
    slug: "merge-pdf",
    href: "/merge-pdf",
    description: "Combine multiple PDF files into one clean packet.",
  },
  {
    name: "Split PDF",
    slug: "split-pdf",
    href: "/split-pdf",
    description: "Extract pages or split ranges from a PDF file.",
  },
  {
    name: "PDF to Word",
    slug: "pdf-to-word",
    href: "/pdf-to-word",
    description: "Prepare PDF files for editable document work.",
  },
  {
    name: "OCR PDF",
    slug: "ocr-pdf",
    href: "/ocr-pdf",
    description: "Extract text from scanned and image-based PDFs.",
  },
  ],
  zh: [
    {
      name: "JPG 转 PDF",
      slug: "jpg-to-pdf",
      href: "/jpg-to-pdf",
      description: "将图片、照片和扫描图转换为 PDF 文档。",
    },
    {
      name: "压缩 PDF",
      slug: "compress-pdf",
      href: "/compress-pdf",
      description: "减小 PDF 体积，便于邮件、上传和共享。",
    },
    {
      name: "合并 PDF",
      slug: "merge-pdf",
      href: "/merge-pdf",
      description: "将多个 PDF 合并为一个清晰文档包。",
    },
    {
      name: "拆分 PDF",
      slug: "split-pdf",
      href: "/split-pdf",
      description: "提取页面或按范围拆分 PDF 文件。",
    },
    {
      name: "PDF 转 Word",
      slug: "pdf-to-word",
      href: "/pdf-to-word",
      description: "将 PDF 准备为可编辑文档工作流。",
    },
    {
      name: "OCR PDF",
      slug: "ocr-pdf",
      href: "/ocr-pdf",
      description: "从扫描件和图片型 PDF 中提取文字。",
    },
  ],
} as const;

const templateCopy = {
  en: {
    toolEyebrow: "AI Document Platform",
    previewWorkflow: "Preview workflow",
    workflowEyebrow: "Tool workflow",
    workflowTitle: "A realistic flow from upload to output.",
    workflowDescription:
      "These tool pages present the real product workflow states users expect before the processing engine is connected.",
    benefits: "Benefits",
    features: "Features",
    workflow: "Workflow",
    faq: "FAQ",
    relatedTools: "Related Tools",
    relatedTitle: "Continue with another PDF workflow.",
    relatedDescription:
      "Move between DockDocs PDF tools without leaving the product platform.",
    indexingEyebrow: "Recommended reading",
    indexingTitle: "Related guides and support for this workflow.",
    indexingDescription:
      "Continue from the tool page into crawlable DockDocs guides, resources, help content, and AI-readable workflow hubs.",
  },
  zh: {
    toolEyebrow: "AI 文档平台",
    previewWorkflow: "预览流程",
    workflowEyebrow: "工具流程",
    workflowTitle: "从上传到导出的真实流程。",
    workflowDescription:
      "工作区展示用户期望看到的上传、处理、结果和下载状态。",
    benefits: "优势",
    features: "功能",
    workflow: "工作流",
    faq: "常见问题",
    relatedTools: "相关工具",
    relatedTitle: "继续使用其它 PDF 工作流。",
    relatedDescription: "在 DockDocs 文档工作区之间继续处理文件。",
    indexingEyebrow: "推荐阅读",
    indexingTitle: "与当前工作流相关的指南和支持内容。",
    indexingDescription:
      "从工具页继续进入 DockDocs 指南、资源、帮助内容和 AI 可读取的工作流中心。",
  },
  es: {
    toolEyebrow: "Plataforma de documentos con IA",
    previewWorkflow: "Ver el flujo de trabajo",
    workflowEyebrow: "Flujo de la herramienta",
    workflowTitle: "Un flujo realista, de la carga al resultado.",
    workflowDescription:
      "Estas páginas presentan los estados reales del flujo de trabajo del producto.",
    benefits: "Ventajas",
    features: "Funciones",
    workflow: "Flujo de trabajo",
    faq: "Preguntas frecuentes",
    relatedTools: "Herramientas relacionadas",
    relatedTitle: "Continúa con otro flujo de trabajo de PDF.",
    relatedDescription:
      "Pasa entre las herramientas de PDF de DockDocs sin salir de la plataforma.",
    indexingEyebrow: "Lecturas recomendadas",
    indexingTitle: "Guías y recursos relacionados con este flujo de trabajo.",
    indexingDescription:
      "Continúa desde la página de la herramienta hacia guías, recursos y contenido de ayuda de DockDocs.",
  },
  pt: {
    toolEyebrow: "Plataforma de documentos com IA",
    previewWorkflow: "Ver o fluxo de trabalho",
    workflowEyebrow: "Fluxo da ferramenta",
    workflowTitle: "Um fluxo realista, do upload ao resultado.",
    workflowDescription:
      "Estas páginas apresentam os estados reais do fluxo de trabalho do produto.",
    benefits: "Vantagens",
    features: "Funcionalidades",
    workflow: "Fluxo de trabalho",
    faq: "Perguntas frequentes",
    relatedTools: "Ferramentas relacionadas",
    relatedTitle: "Continue com outro fluxo de trabalho de PDF.",
    relatedDescription:
      "Alterne entre as ferramentas de PDF do DockDocs sem sair da plataforma.",
    indexingEyebrow: "Leitura recomendada",
    indexingTitle: "Guias e recursos relacionados a este fluxo de trabalho.",
    indexingDescription:
      "Continue da página da ferramenta para guias, recursos e conteúdo de ajuda do DockDocs.",
  },
  fr: {
    toolEyebrow: "Plateforme de documents IA",
    previewWorkflow: "Aperçu du flux de travail",
    workflowEyebrow: "Flux de l'outil",
    workflowTitle: "Un flux réaliste, du chargement au résultat.",
    workflowDescription:
      "Ces pages présentent les états réels du flux de travail du produit.",
    benefits: "Avantages",
    features: "Fonctionnalités",
    workflow: "Flux de travail",
    faq: "Questions fréquentes",
    relatedTools: "Outils associés",
    relatedTitle: "Continuez avec un autre flux PDF.",
    relatedDescription:
      "Passez d'un outil DockDocs à l'autre sans quitter la plateforme.",
    indexingEyebrow: "Lectures recommandées",
    indexingTitle: "Guides et ressources liés à ce flux de travail.",
    indexingDescription:
      "Poursuivez depuis la page de l'outil vers les guides, ressources et contenus d'aide DockDocs.",
  },
  ja: {
    toolEyebrow: "AI ドキュメントプラットフォーム",
    previewWorkflow: "ワークフローをプレビュー",
    workflowEyebrow: "ツールのワークフロー",
    workflowTitle: "アップロードから出力までの実際のフロー。",
    workflowDescription:
      "これらのページは、製品の実際のワークフローの状態を示しています。",
    benefits: "メリット",
    features: "機能",
    workflow: "ワークフロー",
    faq: "よくある質問",
    relatedTools: "関連ツール",
    relatedTitle: "別の PDF ワークフローを続ける。",
    relatedDescription:
      "プラットフォームから離れることなく、DockDocs の PDF ツール間を移動できます。",
    indexingEyebrow: "おすすめの記事",
    indexingTitle: "このワークフローに関連するガイドとリソース。",
    indexingDescription:
      "ツールページから DockDocs のガイド、リソース、ヘルプコンテンツへ続けて進めます。",
  },
  de: {
    toolEyebrow: "KI-Dokumentplattform",
    previewWorkflow: "Workflow-Vorschau",
    workflowEyebrow: "Tool-Workflow",
    workflowTitle: "Ein realistischer Ablauf vom Upload bis zum Ergebnis.",
    workflowDescription:
      "Diese Seiten zeigen die realen Workflow-Zustände des Produkts.",
    benefits: "Vorteile",
    features: "Funktionen",
    workflow: "Workflow",
    faq: "Häufige Fragen",
    relatedTools: "Verwandte Tools",
    relatedTitle: "Mit einem weiteren PDF-Workflow fortfahren.",
    relatedDescription:
      "Wechseln Sie zwischen den PDF-Tools von DockDocs, ohne die Plattform zu verlassen.",
    indexingEyebrow: "Empfohlene Lektüre",
    indexingTitle: "Anleitungen und Ressourcen zu diesem Workflow.",
    indexingDescription:
      "Gehen Sie von der Tool-Seite weiter zu Anleitungen, Ressourcen und Hilfeinhalten von DockDocs.",
  },
} as const;

type TplLocale = "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko" | "zh-Hant";
// templateCopy accessor: zh-Hant derives from zh via OpenCC; de is authored natively;
// ko has no templateCopy block yet → falls back to en (foundation phase).
function tlCopy(locale: TplLocale): (typeof templateCopy)["en"] {
  if (locale === "zh-Hant") return deepHantTpl(templateCopy.zh) as unknown as (typeof templateCopy)["en"];
  return (templateCopy[locale as keyof typeof templateCopy] ?? templateCopy.en) as unknown as (typeof templateCopy)["en"];
}

export function createPdfToolMetadata(config: PdfToolPageConfig): Metadata {
  const canonicalPath = config.canonicalPath ?? `/${config.slug}/`;
  const pageUrl = `${siteUrl}${canonicalPath}`;
  const title = config.title.replace(/\s*\|\s*DockDocs\s*$/u, "");

  return {
    title,
    description: config.description,
    keywords: config.keywords,
    alternates: {
      canonical: canonicalPath,
      languages: config.alternateLanguages,
    },
    openGraph: {
      title,
      description: config.description,
      url: pageUrl,
      siteName: "DockDocs",
      type: "website",
      images: [{ url: `${siteUrl}/opengraph-image`, width: 1200, height: 630, alt: "DockDocs — every tool you need for PDFs" }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: config.description,
      images: [`${siteUrl}/opengraph-image`],
    },
    robots: {
      index: true,
      follow: true,
    },
  };
}

export function createPdfToolSchema(config: PdfToolPageConfig) {
  const canonicalPath = config.canonicalPath ?? `/${config.slug}/`;
  const pageUrl = `${siteUrl}${canonicalPath}`;
  const toolDate = toolDates[config.slug] ?? {};
  const schemaLocale = config.locale ?? "en";
  const schemaTr = (en: string, zh: string, es: string, pt: string, fr: string, ja: string): string =>
    schemaLocale === "zh-Hant"
      ? ccTpl(zh)
      : // de/ko have no authored schema copy → English fallback (GAP: de/ko schema strings).
        schemaLocale === "de" || schemaLocale === "ko"
        ? en
        : ({ en, zh, es, pt, fr, ja })[schemaLocale];

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${pageUrl}#webpage`,
        url: pageUrl,
        name: config.title,
        description: config.description,
        // Real git dates (omitted if unavailable — never fabricated).
        ...(toolDate.datePublished ? { datePublished: toolDate.datePublished } : {}),
        ...(toolDate.dateModified ? { dateModified: toolDate.dateModified } : {}),
        // IndexingLinks target en-only surfaces (/guides, /blog, /resources +
        // their items). Use canonical non-prefixed URLs — a /pt|es|fr tool page
        // must NOT link to /pt/guides/… etc. (those locale variants don't exist → 404).
        significantLink: getIndexingLinks(config).map((link) =>
          absoluteHref(link.href),
        ),
        isPartOf: {
          "@type": "WebSite",
          name: "DockDocs",
          url: siteUrl,
        },
        publisher: { "@type": "Organization", "@id": `${siteUrl}#org` },
        about: {
          "@id": `${pageUrl}#app`,
        },
        breadcrumb: {
          "@id": `${pageUrl}#breadcrumb`,
        },
      },
      {
        "@type": "WebApplication",
        "@id": `${pageUrl}#app`,
        name: config.schemaName,
        applicationCategory: "BusinessApplication",
        operatingSystem: "Web",
        url: pageUrl,
        description: config.description,
        featureList: config.keywords,
        brand: {
          "@type": "Brand",
          name: "DockDocs",
          slogan: schemaTr(
            "AI document platform for real file workflows",
            "面向真实文件工作流的 AI 文档平台",
            "Plataforma de documentos con IA para flujos de trabajo de archivos reales",
            "Plataforma de documentos com IA para fluxos de trabalho de arquivos reais",
            "Plateforme documentaire IA pour les vrais flux de travail sur fichiers",
            "実際のファイル業務のための AI ドキュメントプラットフォーム",
          ),
        },
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
      },
      {
        "@type": "HowTo",
        "@id": `${pageUrl}#howto`,
        name: schemaTr(
          `How to use ${config.appName}`,
          `如何使用 ${config.appName}`,
          `Cómo usar ${config.appName}`,
          `Como usar ${config.appName}`,
          `Comment utiliser ${config.appName}`,
          `${config.appName} の使い方`,
        ),
        description: config.workflowDescription,
        step: config.steps.map((step, index) => ({
          "@type": "HowToStep",
          position: index + 1,
          text: step,
        })),
      },
      {
        "@type": "FAQPage",
        "@id": `${pageUrl}#faq`,
        mainEntity: config.faq.map((faq) => ({
          "@type": "Question",
          name: faq.question,
          acceptedAnswer: {
            "@type": "Answer",
            text: faq.answer,
          },
        })),
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${pageUrl}#breadcrumb`,
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "DockDocs",
            item: siteUrl,
          },
          {
            "@type": "ListItem",
            position: 2,
            name: config.breadcrumbName,
            item: pageUrl,
          },
        ],
      },
    ],
  };
}

// Standalone JSON-LD script for tool pages that render a custom *Client.tsx
// instead of <PdfToolPage> (e.g. merge/split/images-to-pdf visual editors).
// Those custom render paths bypass createPdfToolSchema, so drop this in
// alongside the client to keep structured data (GEO) coverage complete.
export function ToolJsonLd({ config }: { config: PdfToolPageConfig }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(createPdfToolSchema(config)),
      }}
    />
  );
}

// Maps the fixed English stats vocabulary to Chinese, so localized tool
// pages show translated pills without editing every tool config.
const STAT_ZH: Record<string, string> = {
  Price: "价格",
  Input: "输入",
  Output: "输出",
  Workspace: "工作区",
  Free: "免费",
  "PDF files": "PDF 文件",
  "PDF file": "PDF 文件",
  PDF: "PDF",
  "Multiple PDFs": "多个 PDF",
  "One PDF": "一个 PDF",
  "Pages or ranges": "页面或范围",
  "Word documents": "Word 文档",
  "Scanned PDFs": "扫描版 PDF",
  "Extracted text": "提取的文字",
  "JPG images": "JPG 图片",
  "PNG images": "PNG 图片",
  "PDF document": "PDF 文档",
  "TXT file": "TXT 文件",
  "Markdown (.md)": "Markdown (.md)",
  "Trimmed PDF": "精简后的 PDF",
  "Rotated PDF": "旋转后的 PDF",
  "Reordered PDF": "重排后的 PDF",
  "PDF + blank page": "PDF + 空白页",
  "Encrypted PDF": "加密 PDF",
  "AI documents": "AI 文档",
  "DOCX / DOC": "DOCX / DOC",
  "PPTX / PPT": "PPTX / PPT",
  "XLSX / XLS": "XLSX / XLS",
  XLSX: "XLSX",
};

function tStat(text: string, zh: boolean): string {
  if (!zh) return text;
  return STAT_ZH[text] ?? text;
}

export function PdfToolPage({ config }: { config: PdfToolPageConfig }) {
  const schema = createPdfToolSchema(config);
  const zh = (config.locale ?? "en") === "zh";

  return (
    <main className="bg-[color:var(--background)] text-[color:var(--foreground)]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />

      {/* ── Hero + Upload ── */}
      <section>
        <div className="mx-auto max-w-5xl px-5 pb-12 pt-12 sm:px-6 lg:px-8 sm:pt-16">
          {/* Title */}
          <h1 className="text-[30px] font-normal leading-[1.1] tracking-[-0.025em] text-[color:var(--foreground)] sm:text-[40px]">
            {config.breadcrumbName}
          </h1>
          <p className="mt-4 text-[16px] leading-[1.6] text-[color:var(--muted)]">
            {config.heroDescription}
          </p>

          {/* Upload engine */}
          <div className="mt-8">
            <PdfWorkflowEngine config={config} />
          </div>
        </div>
      </section>

      {/* ── Benefits · How-it-works (crawlable depth; skipped if a config has none) ── */}
      {config.benefits.length > 0 && <BenefitsSection config={config} />}
      {config.steps.length > 0 && <HowItWorksSection config={config} />}

      {/* ── FAQ (collapsed, clean) ── */}
      {config.faq.length > 0 && (
        <section>
          <div className="mx-auto max-w-5xl px-5 py-10 sm:px-6 lg:px-8">
            <h2 className="text-[22px] font-normal tracking-[-0.02em] text-[color:var(--foreground)] sm:text-[26px]">{config.faqTitle}</h2>
            <div className="mt-6 space-y-6">
              {config.faq.map((item) => (
                <div key={item.question}>
                  <h3 className="text-[15px] font-medium text-[color:var(--foreground)]">{item.question}</h3>
                  <p className="mt-2 text-sm leading-6 text-[color:var(--muted)]">{item.answer}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* ── Verifiable-trust proof: only on tools that upload nothing (gated) ── */}
      {LOCAL_ONLY_SLUGS.has(config.slug) && (
        <Section bordered={false}>
          <Container className="!max-w-5xl">
            <VerifyClientSide locale={config.locale ?? "en"} />
          </Container>
        </Section>
      )}

      {/* ── Recommended reading (crawlable internal links; SEO-reconciled to survivors) ── */}
      <IndexingLinksSection config={config} />
    </main>
  );
}

function HeroSection({ config }: { config: PdfToolPageConfig }) {
  const copy = tlCopy(config.locale ?? "en");

  return (
    <Section className="border-b border-[color:var(--line)] bg-[color:var(--surface)] py-0">
      <Container className="grid min-h-[72vh] items-center gap-12 py-16 lg:grid-cols-[1.05fr_0.95fr] lg:py-24">
        <div>
          <div className="inline-flex rounded-full border border-[color:var(--line)] bg-[color:var(--surface)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-[color:var(--muted)] shadow-sm">
            {copy.toolEyebrow}
          </div>
          <h1 className="mt-6 max-w-4xl break-words text-2xl font-semibold leading-[1.08] sm:text-6xl sm:leading-[1.04]">
            {config.heroTitle}
          </h1>
          <p className="mt-6 max-w-2xl text-base leading-8 text-[color:var(--muted)] sm:text-lg">
            {config.heroDescription}
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <ButtonLink
              href="#upload"
              className="shadow-[0_10px_24px_rgba(23,23,23,0.16)]"
            >
              {config.primaryActionLabel}
            </ButtonLink>
            <ButtonLink href="#workflow-preview" variant="outline" className="bg-[color:var(--surface)]">
              {copy.previewWorkflow}
            </ButtonLink>
          </div>
          <dl className="mt-10 grid max-w-2xl gap-3 sm:grid-cols-3">
            {config.stats.map(([label, value]) => (
              <div
                key={label}
                className="rounded-[var(--radius-sm)] border border-[color:var(--line)] bg-[color:var(--surface)] px-4 py-3 shadow-sm"
              >
                <dt className="text-xs font-semibold uppercase tracking-[0.16em] text-[color:var(--muted)]">
                  {label}
                </dt>
                <dd className="mt-2 text-sm font-semibold text-[color:var(--foreground)]">
                  {value}
                </dd>
              </div>
            ))}
          </dl>
        </div>
        <PdfWorkflowEngine config={config} />
      </Container>
    </Section>
  );
}

function BenefitsSection({ config }: { config: PdfToolPageConfig }) {
  const copy = tlCopy(config.locale ?? "en");

  return (
    <Section bordered={false}>
      <Container className="!max-w-5xl">
        <SectionIntro
          eyebrow={copy.benefits}
          title={config.benefitsTitle}
          description={config.benefitsDescription}
        />
        <div className="mt-10 grid gap-4 sm:grid-cols-3">
          {config.benefits.map((benefit) => (
            <InfoCard key={benefit.title} item={benefit} />
          ))}
        </div>
      </Container>
    </Section>
  );
}

function FeaturesSection({ config }: { config: PdfToolPageConfig }) {
  const copy = tlCopy(config.locale ?? "en");

  return (
    <Section id="features" bordered={false}>
      <Container className="!max-w-5xl">
        <SectionIntro
          eyebrow={copy.features}
          title={config.featuresTitle}
          description={config.featuresDescription}
        />
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {config.features.map((feature) => (
            <InfoCard key={feature.title} item={feature} />
          ))}
        </div>
      </Container>
    </Section>
  );
}

function HowItWorksSection({ config }: { config: PdfToolPageConfig }) {
  const copy = tlCopy(config.locale ?? "en");

  return (
    <Section bordered={false}>
      <Container className="!max-w-5xl">
        <SectionIntro
          eyebrow={copy.workflow}
          title={config.workflowTitle}
          description={config.workflowDescription}
        />
        <ol className="mt-10 grid gap-4 sm:grid-cols-3">
          {config.steps.map((step, index) => (
            <li key={step}>
              <div className="h-full rounded-[var(--radius)] border border-[color:var(--line)] bg-black/20 p-5 transition hover:border-[color:var(--foreground)]">
                <span className="flex h-9 w-9 items-center justify-center rounded-full bg-[color:var(--foreground)] text-sm font-semibold text-[color:var(--background)]">
                  {index + 1}
                </span>
                <p className="mt-4 font-normal text-[color:var(--foreground)]">{step}</p>
              </div>
            </li>
          ))}
        </ol>
      </Container>
    </Section>
  );
}

function RelatedPdfTools({
  currentSlug,
  locale = "en",
  useLocalePrefix = false,
}: {
  currentSlug: string;
  locale?: "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko" | "zh-Hant";
  useLocalePrefix?: boolean;
}) {
  const copy = tlCopy(locale);
  const prefix = `/${locale}`;
  const related = pdfTools[locale === "zh" || locale === "zh-Hant" ? "zh" : "en"].filter((tool) => tool.slug !== currentSlug);

  return (
    <Section id="related-tools" bordered={false}>
      <Container className="!max-w-5xl">
        <SectionIntro
          eyebrow={copy.relatedTools}
          title={copy.relatedTitle}
          description={copy.relatedDescription}
        />
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
          {related.map((tool) => (
            <a
              key={tool.href}
              href={useLocalePrefix ? `${prefix}${tool.href}` : tool.href}
              className="group rounded-[var(--radius)] border border-[color:var(--line)] bg-black/20 p-5 transition hover:-translate-y-0.5 hover:border-[color:var(--foreground)]"
            >
              <div className="flex items-center justify-between gap-4">
                <h3 className="font-normal text-[color:var(--foreground)]">{tool.name}</h3>
                <span className="text-[color:var(--muted)] transition group-hover:translate-x-0.5 group-hover:text-[color:var(--foreground)]">
                  -&gt;
                </span>
              </div>
              <p className="mt-3 text-sm leading-6 text-[color:var(--muted)]">
                {tool.description}
              </p>
            </a>
          ))}
        </div>
      </Container>
    </Section>
  );
}

// 7-locale string picker for the tool-page "Recommended reading" card grid (zh-Hant reuses zh).
type IndexingLocale = "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko" | "zh-Hant";
function indexingTr(
  locale: IndexingLocale,
  en: string,
  zh: string,
  es: string,
  pt: string,
  fr: string,
  ja: string,
  de: string,
): string {
  if (locale === "zh-Hant") return ccTpl(zh);
  // ko → en until Korean copy lands (content phase); the indexingTr callsites are not
  // widened to an 8th Korean argument in this phase.
  if (locale === "ko") return en;
  return ({ en, zh, es, pt, fr, ja, de })[locale];
}

function IndexingLinksSection({ config }: { config: PdfToolPageConfig }) {
  const locale = config.locale ?? "en";
  const copy = tlCopy(locale);
  const links = getIndexingLinks(config);

  return (
    <Section bordered={false}>
      <Container className="!max-w-5xl">
        <SectionIntro
          eyebrow={copy.indexingEyebrow}
          title={copy.indexingTitle}
          description={copy.indexingDescription}
        />
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {links.map((link) => (
            <a
              key={link.href}
              // Canonical non-prefixed href: these guide/blog/resource targets are
              // en-only, so a /pt|es|fr tool page must link to /guides/X (not /pt/guides/X → 404).
              href={localizeTemplateHref(link.href)}
              className="group rounded-[var(--radius)] border border-[color:var(--line)] bg-black/20 p-5 transition hover:-translate-y-0.5 hover:border-[color:var(--foreground)]"
            >
              <h3 className="font-normal text-[color:var(--foreground)]">{link.label}</h3>
              <p className="mt-3 text-sm leading-6 text-[color:var(--muted)]">
                {link.description}
              </p>
              <span className="mt-5 inline-block text-sm font-semibold text-[color:var(--foreground)] transition group-hover:translate-x-0.5">
                {indexingTr(locale, "Continue", "继续阅读", "Continuar", "Continuar", "Continuer", "続きを読む", "Weiterlesen")} -&gt;
              </span>
            </a>
          ))}
        </div>
      </Container>
    </Section>
  );
}

function getIndexingLinks(config: PdfToolPageConfig): IndexingLink[] {
  const locale = (config.locale ?? "en") as IndexingLocale;
  const tr = (en: string, zh: string, es: string, pt: string, fr: string, ja: string, de: string) =>
    indexingTr(locale, en, zh, es, pt, fr, ja, de);
  const common = [
    {
      label: tr("PDF workflow resources", "PDF 工作流资源", "Recursos de flujos de trabajo PDF", "Recursos de fluxos de trabalho PDF", "Ressources de flux de travail PDF", "PDF ワークフローのリソース", "PDF-Workflow-Ressourcen"),
      href: "/resources",
      description: tr(
        "Explore a structured hub for PDF tools, OCR, conversion, and AI document paths.",
        "按工作流整理 PDF 工具、OCR、转换和 AI 文档路径。",
        "Explora un centro estructurado de herramientas PDF, OCR, conversión y rutas de documentos con IA.",
        "Explore um hub estruturado de ferramentas PDF, OCR, conversão e fluxos de documentos com IA.",
        "Explorez un hub structuré d'outils PDF, d'OCR, de conversion et de parcours documentaires IA.",
        "PDF ツール、OCR、変換、AI ドキュメントの導線を整理したハブを見る。",
        "Entdecken Sie einen strukturierten Hub für PDF-Tools, OCR, Konvertierung und KI-Dokumentwege.",
      ),
    },
    {
      label: tr("PDF guides", "PDF 指南", "Guías de PDF", "Guias de PDF", "Guides PDF", "PDF ガイド", "PDF-Anleitungen"),
      href: "/guides",
      description: tr(
        "Read step-by-step guidance for compression, merging, splitting, conversion, and everyday document tasks.",
        "阅读压缩、合并、拆分、转换和日常文档任务的步骤指南。",
        "Lee guías paso a paso de compresión, combinación, división, conversión y tareas cotidianas con documentos.",
        "Leia guias passo a passo de compressão, combinação, divisão, conversão e tarefas diárias com documentos.",
        "Lisez des guides étape par étape pour la compression, la fusion, la division, la conversion et les tâches documentaires courantes.",
        "圧縮、結合、分割、変換、日常的なドキュメント作業の手順ガイドを読む。",
        "Lesen Sie Schritt-für-Schritt-Anleitungen zu Komprimierung, Zusammenfügen, Teilen, Konvertierung und alltäglichen Dokumentaufgaben.",
      ),
    },
    {
      label: tr("Help and FAQ", "帮助与 FAQ", "Ayuda y FAQ", "Ajuda e FAQ", "Aide et FAQ", "ヘルプと FAQ", "Hilfe und FAQ"),
      href: "/help",
      description: tr(
        "Understand uploads, privacy-first handling, local processing, AI limits, and supported formats.",
        "了解上传、隐私优先处理、本地处理、AI 限制和支持格式。",
        "Conoce las cargas, el tratamiento centrado en la privacidad, el procesamiento local, los límites de la IA y los formatos admitidos.",
        "Entenda os uploads, o tratamento com foco em privacidade, o processamento local, os limites da IA e os formatos suportados.",
        "Comprenez les téléversements, le traitement axé sur la confidentialité, le traitement local, les limites de l'IA et les formats pris en charge.",
        "アップロード、プライバシー優先の処理、ローカル処理、AI の制限、対応フォーマットについて理解する。",
        "Verstehen Sie Uploads, datenschutzorientierte Verarbeitung, lokale Verarbeitung, KI-Grenzen und unterstützte Formate.",
      ),
    },
  ];

  const articleLinks: Record<string, IndexingLink[]> = {
    // Slim-down (2026-06-17): every link points to an INDEXABLE survivor guide or a
    // real blog/tool page. The deleted thin /guides pages were removed here too so
    // tool pages no longer re-feed them to Google (and to schema significantLink).
    "compress-pdf": [
      {
        label: tr("Reduce PDF size without losing quality", "无损压缩 PDF 体积", "Reduce el tamaño del PDF sin perder calidad", "Reduza o tamanho do PDF sem perder qualidade", "Réduisez la taille du PDF sans perte de qualité", "品質を落とさずに PDF サイズを縮小", "PDF-Größe ohne Qualitätsverlust reduzieren"),
        href: "/guides/reduce-pdf-size-without-losing-quality",
        description: tr(
          "Shrink a PDF while keeping text and images readable.",
          "在保持文字和图片清晰的前提下减小 PDF 体积。",
          "Reduce un PDF manteniendo el texto y las imágenes legibles.",
          "Reduza um PDF mantendo o texto e as imagens legíveis.",
          "Réduisez un PDF tout en gardant le texte et les images lisibles.",
          "文字と画像を読みやすく保ったまま PDF を縮小します。",
          "Verkleinern Sie ein PDF, während Text und Bilder lesbar bleiben.",
        ),
      },
      {
        label: tr("Compress PDF for Gmail", "Gmail 压缩 PDF", "Comprimir PDF para Gmail", "Comprimir PDF para o Gmail", "Compresser un PDF pour Gmail", "Gmail 向けに PDF を圧縮", "PDF für Gmail komprimieren"),
        href: "/guides/compress-pdf-for-gmail",
        description: tr(
          "Use a Gmail-focused compression workflow before sending attachments.",
          "面向 Gmail 附件限制的压缩流程。",
          "Usa un flujo de compresión orientado a Gmail antes de enviar adjuntos.",
          "Use um fluxo de compressão voltado para o Gmail antes de enviar anexos.",
          "Utilisez un flux de compression adapté à Gmail avant d'envoyer des pièces jointes.",
          "添付ファイルを送る前に Gmail 向けの圧縮ワークフローを使います。",
          "Nutzen Sie einen auf Gmail ausgerichteten Komprimierungs-Workflow, bevor Sie Anhänge senden.",
        ),
      },
      {
        label: tr("Compress multiple PDFs at once", "一次批量压缩多个 PDF", "Comprimir varios PDF a la vez", "Comprimir vários PDF de uma vez", "Compresser plusieurs PDF en une fois", "複数の PDF を一度に圧縮", "Mehrere PDFs auf einmal komprimieren"),
        href: "/guides/batch-compress-pdf",
        description: tr(
          "Compress a whole folder of PDFs in one go.",
          "一次性压缩整个文件夹的 PDF。",
          "Comprime una carpeta entera de PDF de una sola vez.",
          "Comprima uma pasta inteira de PDF de uma só vez.",
          "Compressez un dossier entier de PDF en une seule fois.",
          "フォルダ内の PDF をまとめて一度に圧縮します。",
          "Komprimieren Sie einen ganzen Ordner voller PDFs in einem Durchgang.",
        ),
      },
    ],
    "merge-pdf": [
      {
        label: tr("How to merge PDF files online", "在线合并 PDF 文件", "Cómo combinar archivos PDF en línea", "Como combinar arquivos PDF online", "Comment fusionner des fichiers PDF en ligne", "オンラインで PDF ファイルを結合する方法", "PDF-Dateien online zusammenfügen"),
        href: "/blog/how-to-merge-pdf-files-online",
        description: tr(
          "Learn how multiple PDFs become one organized document packet.",
          "了解多个 PDF 如何变成一个清晰的文档包。",
          "Aprende cómo varios PDF se convierten en un paquete de documentos organizado.",
          "Saiba como vários PDF se tornam um pacote de documentos organizado.",
          "Découvrez comment plusieurs PDF deviennent un dossier de documents organisé.",
          "複数の PDF が 1 つの整理された文書パックになる方法を学びます。",
          "Erfahren Sie, wie aus mehreren PDFs ein geordnetes Dokumentpaket wird.",
        ),
      },
      {
        label: tr("Merge PDFs without losing quality", "无损合并 PDF", "Combinar PDF sin perder calidad", "Combinar PDF sem perder qualidade", "Fusionner des PDF sans perte de qualité", "品質を落とさずに PDF を結合", "PDFs ohne Qualitätsverlust zusammenfügen"),
        href: "/guides/merge-pdfs-without-losing-quality",
        description: tr(
          "Combine PDFs into one file without quality loss.",
          "把多个 PDF 合并成一个文件且不损质量。",
          "Combina varios PDF en un solo archivo sin pérdida de calidad.",
          "Combine vários PDF em um único arquivo sem perda de qualidade.",
          "Combinez plusieurs PDF en un seul fichier sans perte de qualité.",
          "品質を損なわずに複数の PDF を 1 つのファイルに結合します。",
          "Fügen Sie PDFs ohne Qualitätsverlust zu einer Datei zusammen.",
        ),
      },
      {
        label: tr("Convert images to PDF for upload", "图片转 PDF 以便上传", "Convertir imágenes a PDF para subir", "Converter imagens em PDF para upload", "Convertir des images en PDF pour le téléversement", "アップロード用に画像を PDF に変換", "Bilder für den Upload in PDF umwandeln"),
        href: "/guides/convert-images-to-pdf-for-upload",
        description: tr(
          "Turn multiple images into one ordered PDF packet.",
          "把多张图片按顺序整理成一个可提交 PDF。",
          "Convierte varias imágenes en un paquete PDF ordenado.",
          "Transforme várias imagens em um pacote PDF ordenado.",
          "Transformez plusieurs images en un dossier PDF ordonné.",
          "複数の画像を順序付けた 1 つの PDF パックにまとめます。",
          "Verwandeln Sie mehrere Bilder in ein geordnetes PDF-Paket.",
        ),
      },
    ],
    "split-pdf": [
      {
        label: tr("How to split PDF pages", "如何拆分 PDF 页面", "Cómo dividir páginas de PDF", "Como dividir páginas de PDF", "Comment diviser des pages PDF", "PDF ページを分割する方法", "PDF-Seiten teilen"),
        href: "/blog/how-to-split-pdf-pages",
        description: tr(
          "Learn how to extract page ranges and export smaller documents.",
          "了解如何提取页面范围并导出更小的文档。",
          "Aprende a extraer rangos de páginas y exportar documentos más pequeños.",
          "Saiba como extrair intervalos de páginas e exportar documentos menores.",
          "Apprenez à extraire des plages de pages et à exporter des documents plus petits.",
          "ページ範囲を抽出して、より小さな文書として書き出す方法を学びます。",
          "Erfahren Sie, wie Sie Seitenbereiche extrahieren und kleinere Dokumente exportieren.",
        ),
      },
      {
        label: tr("Split a PDF by page ranges", "按页面范围拆分 PDF", "Dividir un PDF por rangos de páginas", "Dividir um PDF por intervalos de páginas", "Diviser un PDF par plages de pages", "ページ範囲で PDF を分割", "PDF nach Seitenbereichen teilen"),
        href: "/guides/split-pdf-page-ranges",
        description: tr(
          "Extract specific page ranges into separate PDFs.",
          "把指定页面范围拆成独立 PDF。",
          "Extrae rangos de páginas específicos en PDF separados.",
          "Extraia intervalos de páginas específicos em PDF separados.",
          "Extrayez des plages de pages spécifiques dans des PDF distincts.",
          "指定したページ範囲を別々の PDF として抽出します。",
          "Extrahieren Sie bestimmte Seitenbereiche in separate PDFs.",
        ),
      },
      {
        label: tr("Reduce PDF size without losing quality", "无损压缩 PDF 体积", "Reduce el tamaño del PDF sin perder calidad", "Reduza o tamanho do PDF sem perder qualidade", "Réduisez la taille du PDF sans perte de qualité", "品質を落とさずに PDF サイズを縮小", "PDF-Größe ohne Qualitätsverlust reduzieren"),
        href: "/guides/reduce-pdf-size-without-losing-quality",
        description: tr(
          "Shrink the resulting files for portals and upload limits.",
          "为门户和上传限制减小导出文件体积。",
          "Reduce los archivos resultantes para portales y límites de carga.",
          "Reduza os arquivos resultantes para portais e limites de upload.",
          "Réduisez les fichiers obtenus pour les portails et les limites de téléversement.",
          "ポータルやアップロード制限に合わせて生成ファイルを縮小します。",
          "Verkleinern Sie die Ergebnisdateien für Portale und Upload-Grenzen.",
        ),
      },
    ],
    "pdf-to-word": [
      {
        label: tr("PDF to Word for editing", "PDF 转 Word 编辑指南", "PDF a Word para editar", "PDF para Word para edição", "PDF en Word pour l'édition", "編集のための PDF から Word", "PDF zu Word zum Bearbeiten"),
        href: "/blog/pdf-to-word-for-editing",
        description: tr(
          "Learn how to prepare fixed PDFs for editable document workflows.",
          "了解如何把固定 PDF 准备为可编辑文档工作流。",
          "Aprende a preparar PDF fijos para flujos de trabajo de documentos editables.",
          "Saiba como preparar PDF fixos para fluxos de trabalho de documentos editáveis.",
          "Apprenez à préparer des PDF figés pour des flux de documents modifiables.",
          "固定された PDF を編集可能な文書ワークフロー向けに準備する方法を学びます。",
          "Erfahren Sie, wie Sie feste PDFs für bearbeitbare Dokument-Workflows vorbereiten.",
        ),
      },
      {
        label: tr("PDF to an editable Word document", "PDF 转可编辑 Word 文档", "PDF a un documento Word editable", "PDF para um documento Word editável", "PDF en document Word modifiable", "編集可能な Word 文書への PDF", "PDF in ein bearbeitbares Word-Dokument"),
        href: "/guides/pdf-to-word-editable-document",
        description: tr(
          "Convert a PDF into an editable .docx you can revise.",
          "把 PDF 转成可修改的 .docx 文档。",
          "Convierte un PDF en un .docx editable que puedes revisar.",
          "Converta um PDF em um .docx editável que você pode revisar.",
          "Convertissez un PDF en un .docx modifiable que vous pouvez réviser.",
          "PDF を、修正できる編集可能な .docx に変換します。",
          "Konvertieren Sie ein PDF in ein bearbeitbares .docx, das Sie überarbeiten können.",
        ),
      },
      {
        label: tr("Extract text from a PDF with OCR", "用 OCR 从 PDF 提取文字", "Extraer texto de un PDF con OCR", "Extrair texto de um PDF com OCR", "Extraire le texte d'un PDF avec l'OCR", "OCR で PDF から文字を抽出", "Text aus einem PDF per OCR extrahieren"),
        href: "/guides/extract-text-from-pdf-with-ocr",
        description: tr(
          "OCR a scanned PDF first when there is no selectable text.",
          "扫描件没有可选文字时，先做 OCR 再转换。",
          "Aplica OCR a un PDF escaneado primero cuando no hay texto seleccionable.",
          "Aplique OCR a um PDF digitalizado primeiro quando não houver texto selecionável.",
          "Appliquez d'abord l'OCR à un PDF numérisé lorsqu'il n'y a pas de texte sélectionnable.",
          "選択できる文字がない場合は、先にスキャン PDF へ OCR をかけます。",
          "Wenden Sie zuerst OCR auf ein gescanntes PDF an, wenn es keinen auswählbaren Text gibt.",
        ),
      },
    ],
    "ocr-pdf": [
      {
        label: tr("OCR a scanned PDF online", "在线 OCR 扫描 PDF", "Aplicar OCR a un PDF escaneado en línea", "Aplicar OCR a um PDF digitalizado online", "Appliquer l'OCR à un PDF numérisé en ligne", "オンラインでスキャン PDF を OCR", "Gescanntes PDF online per OCR verarbeiten"),
        href: "/guides/ocr-scanned-pdf-online",
        description: tr(
          "Turn scanned, image-only PDFs into selectable text.",
          "把扫描的纯图片 PDF 变成可选文字。",
          "Convierte PDF escaneados y solo de imágenes en texto seleccionable.",
          "Transforme PDF digitalizados e apenas de imagem em texto selecionável.",
          "Transformez des PDF numérisés et uniquement composés d'images en texte sélectionnable.",
          "スキャンした画像のみの PDF を、選択できる文字に変換します。",
          "Verwandeln Sie gescannte, reine Bild-PDFs in auswählbaren Text.",
        ),
      },
      {
        label: tr("Extract text from a PDF with OCR", "用 OCR 从 PDF 提取文字", "Extraer texto de un PDF con OCR", "Extrair texto de um PDF com OCR", "Extraire le texte d'un PDF avec l'OCR", "OCR で PDF から文字を抽出", "Text aus einem PDF per OCR extrahieren"),
        href: "/guides/extract-text-from-pdf-with-ocr",
        description: tr(
          "Extract copyable, searchable text from scanned pages.",
          "从扫描页提取可复制、可搜索的文本。",
          "Extrae texto copiable y con capacidad de búsqueda de páginas escaneadas.",
          "Extraia texto copiável e pesquisável de páginas digitalizadas.",
          "Extrayez du texte copiable et consultable à partir de pages numérisées.",
          "スキャンしたページから、コピー・検索できる文字を抽出します。",
          "Extrahieren Sie kopierbaren, durchsuchbaren Text aus gescannten Seiten.",
        ),
      },
      {
        label: tr("OCR workflow questions", "OCR 工作流常见问题", "Preguntas sobre el flujo de OCR", "Perguntas sobre o fluxo de OCR", "Questions sur le flux OCR", "OCR ワークフローのよくある質問", "Fragen zum OCR-Workflow"),
        href: "/resources/ocr-pdf-workflow-questions",
        description: tr(
          "Common questions about scanning, accuracy, and OCR output.",
          "关于扫描、准确率和 OCR 输出的常见问题。",
          "Preguntas frecuentes sobre el escaneo, la precisión y la salida de OCR.",
          "Perguntas frequentes sobre digitalização, precisão e saída de OCR.",
          "Questions fréquentes sur la numérisation, la précision et le résultat de l'OCR.",
          "スキャン、精度、OCR 出力に関するよくある質問。",
          "Häufige Fragen zu Scannen, Genauigkeit und OCR-Ergebnis.",
        ),
      },
    ],
    "jpg-to-pdf": [
      {
        label: tr("JPG to PDF on iPhone", "iPhone 上 JPG 转 PDF", "JPG a PDF en iPhone", "JPG para PDF no iPhone", "JPG en PDF sur iPhone", "iPhone で JPG を PDF に", "JPG zu PDF auf dem iPhone"),
        href: "/guides/jpg-to-pdf-on-iphone",
        description: tr(
          "Turn iPhone photos into upload-ready PDFs.",
          "将 iPhone 照片整理为可上传 PDF。",
          "Convierte las fotos del iPhone en PDF listos para subir.",
          "Transforme as fotos do iPhone em PDF prontos para upload.",
          "Transformez les photos de l'iPhone en PDF prêts à téléverser.",
          "iPhone の写真を、アップロードできる PDF にします。",
          "Verwandeln Sie iPhone-Fotos in upload-fertige PDFs.",
        ),
      },
      {
        label: tr("Convert images to PDF for upload", "图片转 PDF 以便上传", "Convertir imágenes a PDF para subir", "Converter imagens em PDF para upload", "Convertir des images en PDF pour le téléversement", "アップロード用に画像を PDF に変換", "Bilder für den Upload in PDF umwandeln"),
        href: "/guides/convert-images-to-pdf-for-upload",
        description: tr(
          "Organize photos and pages into one ordered PDF.",
          "把照片和页面整理成一个有序 PDF。",
          "Organiza fotos y páginas en un PDF ordenado.",
          "Organize fotos e páginas em um PDF ordenado.",
          "Organisez photos et pages dans un PDF ordonné.",
          "写真とページを、順序付けた 1 つの PDF にまとめます。",
          "Ordnen Sie Fotos und Seiten in einem geordneten PDF.",
        ),
      },
      {
        label: tr("Image to PDF conversion questions", "图片转 PDF 常见问题", "Preguntas sobre la conversión de imagen a PDF", "Perguntas sobre a conversão de imagem em PDF", "Questions sur la conversion image vers PDF", "画像から PDF への変換のよくある質問", "Fragen zur Bild-zu-PDF-Konvertierung"),
        href: "/resources/image-to-pdf-conversion-questions",
        description: tr(
          "Common questions about formats, order, and image-to-PDF output.",
          "关于格式、顺序和图片转 PDF 输出的常见问题。",
          "Preguntas frecuentes sobre formatos, orden y salida de imagen a PDF.",
          "Perguntas frequentes sobre formatos, ordem e saída de imagem para PDF.",
          "Questions fréquentes sur les formats, l'ordre et le résultat image vers PDF.",
          "フォーマット、順序、画像から PDF への出力に関するよくある質問。",
          "Häufige Fragen zu Formaten, Reihenfolge und Bild-zu-PDF-Ergebnis.",
        ),
      },
    ],
  };

  return [...(articleLinks[config.slug] ?? []), ...common];
}

function localizeTemplateHref(href: string, locale?: "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko" | "zh-Hant") {
  const clean = href === "/" ? "" : href.replace(/\/+$/g, "");
  const path = clean ? `${clean}/` : "/";

  if (!locale) {
    return path;
  }

  return path === "/" ? `/${locale}/` : `/${locale}${path}`;
}

function absoluteHref(href: string, locale?: "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko" | "zh-Hant") {
  return `${siteUrl}${localizeTemplateHref(href, locale)}`;
}

function SectionIntro({
  eyebrow,
  title,
  description,
}: {
  eyebrow: string;
  title: string;
  description?: string;
}) {
  return (
    <div className="max-w-2xl">
      <p className="font-mono text-[12px] uppercase tracking-[0.08em] text-[color:var(--faint)]">
        // {eyebrow}
      </p>
      <h2 className="mt-4 text-[28px] font-normal leading-[1.15] tracking-[-0.02em] text-[color:var(--foreground)] sm:text-[36px]">
        <span className="break-words">{title}</span>
      </h2>
      {description ? (
        <p className="mt-4 leading-7 text-[color:var(--muted)]">{description}</p>
      ) : null}
    </div>
  );
}

function InfoCard({ item }: { item: PdfToolItem }) {
  return (
    <div className="h-full rounded-[var(--radius)] border border-[color:var(--line)] bg-black/20 p-5 transition hover:border-[color:var(--foreground)]">
      <h3 className="break-words text-[15px] font-medium text-[color:var(--foreground)]">{item.title}</h3>
      <p className="mt-3 text-sm leading-6 text-[color:var(--muted)]">
        {item.description}
      </p>
    </div>
  );
}

function ProgressPreview({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="flex items-center justify-between gap-4">
        <span className="font-medium text-[color:var(--foreground)]">{label}</span>
        <span>{value}</span>
      </div>
      <div className="mt-3 h-2 rounded-full bg-[color:var(--surface)]">
        <div className="h-2 w-2/3 rounded-full bg-[color:var(--foreground)]" />
      </div>
    </div>
  );
}

function FileListPreview({ files }: { files: string[] }) {
  return (
    <ol className="space-y-2">
      {files.map((file, index) => (
        <li
          key={file}
          className="flex items-center justify-between gap-3 rounded-[var(--radius-sm)] border border-[color:var(--line)] bg-[color:var(--surface)] px-3 py-2"
        >
          <span className="font-medium text-[color:var(--foreground)]">{file}</span>
          <span className="text-xs text-[color:var(--muted)]">#{index + 1}</span>
        </li>
      ))}
    </ol>
  );
}

function RangePreview() {
  return (
    <label className="block">
      <span className="text-xs font-semibold uppercase tracking-[0.14em] text-[color:var(--muted)]">
        Page ranges
      </span>
      <input
        readOnly
        value="1-4, 12-18, 30"
        className="mt-2 w-full rounded-[var(--radius-sm)] border border-[color:var(--line)] bg-[color:var(--surface)] px-3 py-2 font-medium text-[color:var(--foreground)]"
      />
    </label>
  );
}

function TextOutputPreview() {
  return (
    <textarea
      readOnly
      rows={4}
      value={
        "Invoice total: $248.00\nDue date: May 31, 2026\nVendor: DockDocs sample scan"
      }
      className="w-full resize-none rounded-[var(--radius-sm)] border border-[color:var(--line)] bg-[color:var(--surface)] p-3 leading-6 text-[color:var(--foreground)]"
    />
  );
}

function DocumentPreview() {
  return (
    <div className="rounded-[var(--radius-sm)] border border-[color:var(--line)] bg-[color:var(--surface)] p-3 text-[color:var(--foreground)]">
      <p className="font-semibold">Editable contract draft</p>
      <p className="mt-2 text-xs leading-5 text-[color:var(--muted)]">
        Heading, paragraphs, and table structure detected for DOCX export.
      </p>
    </div>
  );
}

function ImageOrderPreview() {
  return (
    <div className="grid grid-cols-3 gap-2">
      {["receipt-1.jpg", "receipt-2.png", "notes.webp"].map((file, index) => (
        <div
          key={file}
          className="rounded-[var(--radius-sm)] border border-[color:var(--line)] bg-[color:var(--surface)] p-2 text-center"
        >
          <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-[var(--radius-sm)] bg-[color:var(--foreground)] text-xs font-semibold text-[color:var(--background)]">
            {index + 1}
          </div>
          <p className="mt-2 break-all text-xs leading-4">{file}</p>
        </div>
      ))}
    </div>
  );
}

function getWorkflowStates(config: PdfToolPageConfig): WorkflowState[] {
  const locale = config.locale ?? "en";
  const zh = locale === "zh";

  switch (config.slug) {
    case "compress-pdf":
      return [
        {
          status: zh ? "上传" : "Upload",
          title: zh ? "上传 PDF" : "Upload PDF",
          description: zh ? "选择 PDF，并在压缩前查看文件大小。" : "Choose a PDF and review file size before compression.",
          preview: "quarterly-report.pdf - 12.4 MB",
        },
        {
          status: zh ? "压缩中" : "Compressing",
          title: zh ? "正在优化" : "Optimization running",
          description: zh ? "流程展示文件体积优化和处理进度。" : "The workflow simulates image cleanup and file-size reduction.",
          preview: <ProgressPreview label={zh ? "正在压缩" : "Compressing"} value="68%" />,
        },
        {
          status: zh ? "结果" : "Result",
          title: zh ? "下载压缩后的 PDF" : "Download compressed PDF",
          description: zh ? "结果状态提供明确下载按钮。" : "A clear result state prepares the user for a download CTA.",
          preview: "quarterly-report-compressed.pdf - 6.4 MB",
          actionLabel: zh ? "下载压缩 PDF" : "Download compressed PDF",
        },
      ];
    case "merge-pdf":
      return [
        {
          status: zh ? "多文件" : "Multi-file",
          title: zh ? "上传多个 PDF" : "Upload multiple PDFs",
          description: zh ? "添加多个文件，准备合并为一个文档包。" : "Add several files and prepare them for one merged packet.",
          preview: "proposal.pdf + invoice.pdf + appendix.pdf",
        },
        {
          status: zh ? "排序" : "Reorder",
          title: zh ? "调整文档顺序" : "Arrange document order",
          description: zh ? "排序列表展示最终合并顺序。" : "A simulated reorder list shows how final packets are assembled.",
          preview: (
            <FileListPreview
              files={["proposal.pdf", "invoice.pdf", "appendix.pdf"]}
            />
          ),
        },
        {
          status: zh ? "结果" : "Result",
          title: zh ? "下载合并后的 PDF" : "Download merged PDF",
          description: zh ? "最终状态指向一个有序输出文件。" : "The final state points users to one organized output file.",
          preview: "client-packet-merged.pdf",
          actionLabel: zh ? "下载合并 PDF" : "Download merged PDF",
        },
      ];
    case "split-pdf":
      return [
        {
          status: zh ? "上传" : "Upload",
          title: zh ? "上传 PDF" : "Upload PDF",
          description: zh ? "选择文件并查看可拆分页数。" : "Choose a file and review the pages available for splitting.",
          preview: "handbook.pdf - 42 pages",
        },
        {
          status: zh ? "范围" : "Range",
          title: zh ? "输入页面范围" : "Enter page ranges",
          description: zh ? "清晰的范围输入帮助用户提取特定页面。" : "A clear range field helps users extract focused sections.",
          preview: <RangePreview />,
        },
        {
          status: zh ? "导出" : "Export",
          title: zh ? "下载拆分 ZIP" : "Download split ZIP",
          description: zh ? "拆分结果以 ZIP 形式导出。" : "Split outputs are grouped as a ZIP-ready export.",
          preview: "handbook-split-pages.zip",
          actionLabel: zh ? "导出 ZIP" : "Export ZIP",
        },
      ];
    case "pdf-to-word":
      return [
        {
          status: zh ? "上传" : "Upload",
          title: zh ? "上传 PDF" : "Upload PDF",
          description: zh ? "选择 PDF 并准备转换为可编辑文档。" : "Choose a PDF and prepare it for editable document conversion.",
          preview: "contract.pdf",
        },
        {
          status: zh ? "转换中" : "Converting",
          title: zh ? "生成 Word 结构" : "Build Word structure",
          description: zh ? "流程展示文本、标题和布局转换。" : "The flow simulates text, headings, and layout conversion.",
          preview: <ProgressPreview label={zh ? "正在转换 DOCX" : "Converting to DOCX"} value="72%" />,
        },
        {
          status: zh ? "预览" : "Preview",
          title: zh ? "可编辑文档输出" : "Editable document output",
          description: zh ? "Word 风格预览让用户在下载前理解结果。" : "A Word-ready preview gives users confidence before download.",
          preview: <DocumentPreview />,
          actionLabel: zh ? "下载 .docx" : "Download .docx",
        },
      ];
    case "ocr-pdf":
      return [
        {
          status: zh ? "上传" : "Upload",
          title: zh ? "上传扫描 PDF" : "Upload scanned PDF",
          description: zh ? "选择扫描件或图片型 PDF 进行文字提取。" : "Choose a scanned file or image-based PDF for text extraction.",
          preview: "scanned-receipts.pdf",
        },
        {
          status: "OCR",
          title: zh ? "提取文字" : "Extract text",
          description: zh ? "流程展示 OCR 识别和文本输出。" : "The workflow simulates OCR detection and clean text output.",
          preview: <ProgressPreview label={zh ? "正在识别文字" : "Recognizing text"} value="81%" />,
        },
        {
          status: zh ? "文本" : "Text",
          title: zh ? "复制或下载文本" : "Copy or download text",
          description: zh ? "结果状态提供复制文本和下载文本操作。" : "The result state includes copy text and download text actions.",
          preview: <TextOutputPreview />,
          actionLabel: zh ? "复制提取文本" : "Copy extracted text",
          secondaryActionLabel: zh ? "下载文本" : "Download text",
        },
      ];
    case "jpg-to-pdf":
      return [
        {
          status: zh ? "图片" : "Images",
          title: zh ? "上传 JPG、PNG 或 WebP" : "Upload JPG, PNG, or WebP",
          description: zh ? "添加照片、扫描图或图片文件用于创建 PDF。" : "Add photos, scans, or image files for document creation.",
          preview: "receipt-1.jpg + receipt-2.png + notes.webp",
        },
        {
          status: zh ? "排序" : "Order",
          title: zh ? "调整页面顺序" : "Arrange page order",
          description: zh ? "图片页面预览展示导出前的顺序。" : "A simulated preview shows image pages before PDF export.",
          preview: <ImageOrderPreview />,
        },
        {
          status: zh ? "导出" : "Export",
          title: zh ? "下载 PDF" : "Download PDF",
          description: zh ? "最终状态提供单个 PDF 导出按钮。" : "The final state prepares a single PDF export CTA.",
          preview: "photos-to-document.pdf",
          actionLabel: zh ? "导出 PDF" : "Export PDF",
        },
      ];
    default:
      return [
        {
          status: "Upload",
          title: "Upload document",
          description: "Choose a file and prepare it for the selected workflow.",
          preview: "Document selected",
        },
        {
          status: "Process",
          title: "Process workflow",
          description: "The tool simulates the document action step.",
          preview: "Processing...",
        },
        {
          status: "Result",
          title: "Download result",
          description: "The result state prepares users for final export.",
          preview: "Output ready",
        },
      ];
  }
}
