"use client";
import { trackToolRun } from "@/lib/track";
import { ToolFaq } from "@/components/ToolFaq";
import { ToolSections, type ToolSectionsContent } from "@/components/ToolSections";
import { UploadDropzone } from "@/components/UploadDropzone";
import { WorkspaceValueZone } from "@/components/WorkspaceValueZone";

import { useCallback, useRef, useState } from "react";
import { Spinner } from "@/components/Spinner";
import { encryptedPdfMessage } from "@/lib/pdf-errors";
import { authHeader } from "@/lib/supabase";
import { checkUsage, markUsage } from "@/lib/usage-gate";
import { UpgradePrompt } from "@/components/ui/UpgradePrompt";
import { deepHant } from "@/lib/zh-hant";
import type { RouteLocale, AuthoredLocale } from "@/lib/i18n";

type Locale = RouteLocale;
type Card ={ q: string; a: string };

const _en = {
  title: "PDF Flashcards",
  subtitle: "Upload a textbook chapter, lecture notes, or a manual and turn it into study flashcards — questions and answers drawn only from your document. Flip a card to check yourself.",
  drop: "Drag & drop a PDF here, or click to choose",
  choose: "Choose PDF", reading: "Reading…", count: "Cards", change: "Replace",
  generate: "Generate cards", generating: "Generating…", reset: "Start over",
  flip: "Tap to flip", question: "Q", answer: "A",
  noText: "No text found in this PDF. If it's a scan, run OCR first.",
  err: "Something went wrong: ",
  note: "Cards are generated by AI from your document. Give them a quick check before studying.",
};

const STR = {
  en: _en,
  zh: {
    title: "PDF 抽认卡",
    subtitle: "上传课本章节、讲义或手册，把它变成学习抽认卡——问题和答案只来自你的文档。点卡片翻面自测。",
    drop: "把 PDF 拖到这里，或点击选择",
    choose: "选择 PDF", reading: "读取中…", count: "卡片数", change: "替换",
    generate: "生成卡片", generating: "生成中…", reset: "重新开始",
    flip: "点击翻面", question: "问", answer: "答",
    noText: "这个 PDF 里没有文字。如果是扫描件，请先 OCR。",
    err: "出错了：",
    note: "卡片由 AI 从你的文档生成，学习前请快速核对。",
  },
  es: {
    title: "Tarjetas de estudio PDF",
    subtitle: "Sube el capítulo de un libro de texto, apuntes de clase o un manual y conviértelo en tarjetas de estudio — preguntas y respuestas extraídas únicamente de tu documento. Toca una tarjeta para girarla y ponerte a prueba.",
    drop: "Arrastra y suelta un PDF aquí, o haz clic para elegir",
    choose: "Elegir PDF", reading: "Leyendo…", count: "Tarjetas", change: "Reemplazar",
    generate: "Generar tarjetas", generating: "Generando…", reset: "Empezar de nuevo",
    flip: "Toca para girar", question: "P", answer: "R",
    noText: "No se encontró texto en este PDF. Si es un escaneo, ejecuta primero el OCR.",
    err: "Algo salió mal: ",
    note: "Las tarjetas las genera la IA a partir de tu documento. Revísalas rápidamente antes de estudiar.",
  },
  pt: {
    title: "Flashcards de PDF",
    subtitle: "Envie um capítulo de livro didático, notas de aula ou um manual e transforme-o em flashcards de estudo — perguntas e respostas extraídas apenas do seu documento. Toque em um cartão para virar e se testar.",
    drop: "Arraste e solte um PDF aqui, ou clique para escolher",
    choose: "Escolher PDF", reading: "Lendo…", count: "Cartões", change: "Substituir",
    generate: "Gerar cartões", generating: "Gerando…", reset: "Recomeçar",
    flip: "Toque para virar", question: "P", answer: "R",
    noText: "Nenhum texto encontrado neste PDF. Se for um documento digitalizado, execute o OCR primeiro.",
    err: "Algo deu errado: ",
    note: "Os cartões são gerados pela IA a partir do seu documento. Verifique-os rapidamente antes de estudar.",
  },
  fr: {
    title: "Fiches de révision PDF",
    subtitle: "Importez un chapitre de manuel, des notes de cours ou un guide et transformez-les en fiches de révision — questions et réponses tirées uniquement de votre document. Retournez une fiche pour vous tester.",
    drop: "Glissez-déposez un PDF ici, ou cliquez pour choisir",
    choose: "Choisir un PDF", reading: "Lecture…", count: "Fiches", change: "Remplacer",
    generate: "Générer les fiches", generating: "Génération…", reset: "Recommencer",
    flip: "Appuyez pour retourner", question: "Q", answer: "R",
    noText: "Aucun texte trouvé dans ce PDF. S'il s'agit d'un scan, effectuez d'abord une reconnaissance OCR.",
    err: "Une erreur est survenue : ",
    note: "Les fiches sont générées par l'IA à partir de votre document. Vérifiez-les rapidement avant de commencer à étudier.",
  },
  ja: {
    title: "PDFフラッシュカード",
    subtitle: "教科書の章・講義ノート・マニュアルをアップロードして学習用フラッシュカードに変換します——問題と回答は文書の内容のみから作られます。カードをタップして自己確認できます。",
    drop: "PDFをここにドラッグ＆ドロップ、またはクリックして選択",
    choose: "PDFを選択", reading: "読み取り中…", count: "枚数", change: "差し替え",
    generate: "カードを生成", generating: "生成中…", reset: "最初からやり直す",
    flip: "タップして裏返す", question: "問", answer: "答",
    noText: "このPDFにテキストが見つかりません。スキャンの場合は先にOCRをかけてください。",
    err: "問題が発生しました: ",
    note: "カードは文書からAIが生成します。学習前に簡単に確認してください。",
  },
  de: {
    title: "PDF-Lernkarten",
    subtitle: "Laden Sie ein Lehrbuchkapitel, Vorlesungsnotizen oder ein Handbuch hoch und verwandeln Sie es in Lernkarten — Fragen und Antworten ausschließlich aus Ihrem Dokument. Drehen Sie eine Karte um, um sich selbst abzufragen.",
    drop: "Ziehen Sie ein PDF hierher oder klicken Sie zum Auswählen",
    choose: "PDF auswählen", reading: "Wird gelesen…", count: "Karten", change: "Ersetzen",
    generate: "Karten generieren", generating: "Wird generiert…", reset: "Von vorn beginnen",
    flip: "Zum Umdrehen tippen", question: "F", answer: "A",
    noText: "In diesem PDF wurde kein Text gefunden. Falls es sich um einen Scan handelt, führen Sie zuerst OCR aus.",
    err: "Etwas ist schiefgelaufen: ",
    note: "Die Karten werden von der KI aus Ihrem Dokument generiert. Prüfen Sie sie kurz, bevor Sie damit lernen.",
  },
  ko: {
    title: "PDF 플래시카드",
    subtitle: "교과서 단원, 강의 노트, 매뉴얼을 업로드해 학습용 플래시카드로 바꾸세요 — 문제와 답은 오직 당신의 문서에서만 만들어집니다. 카드를 뒤집어 스스로 확인하세요.",
    drop: "여기에 PDF를 끌어다 놓거나 클릭해 선택하세요",
    choose: "PDF 선택", reading: "읽는 중…", count: "카드 수", change: "교체",
    generate: "카드 생성", generating: "생성 중…", reset: "처음부터 다시",
    flip: "탭하여 뒤집기", question: "문", answer: "답",
    noText: "이 PDF에서 텍스트를 찾지 못했습니다. 스캔본이면 먼저 OCR을 실행하세요.",
    err: "문제가 발생했습니다: ",
    note: "카드는 AI가 당신의 문서에서 생성합니다. 학습 전에 한 번 빠르게 확인하세요.",
  },
} satisfies Record<AuthoredLocale, typeof _en>;

const SECTIONS: Record<AuthoredLocale, ToolSectionsContent> = {
  en: {
    benefitsTitle: "Why turn a document into flashcards",
    benefitsDescription: "Study from cards built directly from your own material — the document's text is analyzed by AI to write the questions and answers.",
    benefits: [
      { title: "Cards from your own source", description: "Questions and answers are written from the document you upload, so you revise the exact material you need to know — not a generic deck." },
      { title: "Active recall, not re-reading", description: "Each card hides the answer until you flip it, forcing you to retrieve it from memory — the study method that actually sticks." },
      { title: "Choose how many to make", description: "Ask for 5, 10, 15, or 20 cards to match a quick review or a full chapter, generated from the same text in one pass." },
    ],
    workflowTitle: "How flashcards fit your study",
    workflowDescription: "When you have a chapter, lecture notes, or a manual and want to test yourself instead of just reading it again.",
    steps: [
      "Upload the PDF you want to study from.",
      "Pick how many cards you want, and the AI drafts question-and-answer pairs from the text.",
      "Flip each card to quiz yourself, and give the answers a quick check before relying on them.",
    ],
    readingTitle: "More ways to work with your document",
    readingDescription: "Related AI tools for studying and understanding the same material.",
    readingLinks: [
      { label: "Summarize a PDF", href: "/ai-summary", description: "Condense the chapter into key points before you turn it into cards." },
      { label: "Chat with a PDF", href: "/chat-with-pdf", description: "Ask follow-up questions about anything in the document the cards don't cover." },
      { label: "Document workflow resources", href: "/resources", description: "A structured hub for document tools, conversion, and AI study paths." },
    ],
  },
  zh: {
    benefitsTitle: "为什么把文档变成抽认卡",
    benefitsDescription: "用直接基于你自己资料生成的卡片学习——由 AI 分析文档文字来撰写问题和答案。",
    benefits: [
      { title: "卡片来自你自己的资料", description: "问题和答案都基于你上传的文档撰写，复习的正是你需要掌握的内容，而不是一套通用题库。" },
      { title: "主动回忆，而非反复重读", description: "每张卡片在你翻面前都藏着答案，逼你从记忆里把它取出来——这才是真正记得住的学习法。" },
      { title: "自选生成数量", description: "可要 5、10、15 或 20 张卡片，适配快速复习或整章学习，一次从同一段文字生成。" },
    ],
    workflowTitle: "抽认卡如何融入你的学习",
    workflowDescription: "当你手上有一章内容、讲义或手册，想自测而不只是再读一遍时。",
    steps: [
      "上传你想用来学习的 PDF。",
      "选择想要的卡片数量，AI 会从文字中起草问答对。",
      "翻开每张卡片自测，并在依赖答案前快速核对一遍。",
    ],
    readingTitle: "处理文档的更多方式",
    readingDescription: "用于学习和理解同一份资料的相关 AI 工具。",
    readingLinks: [
      { label: "总结 PDF", href: "/ai-summary", description: "在做成卡片前，先把这一章浓缩成要点。" },
      { label: "与 PDF 对话", href: "/chat-with-pdf", description: "就卡片没覆盖到的内容，向文档继续追问。" },
      { label: "文档工作流资源", href: "/resources", description: "按工作流整理的文档工具、转换和 AI 学习路径中心。" },
    ],
  },
  es: {
    benefitsTitle: "Por qué convertir un documento en tarjetas de estudio",
    benefitsDescription: "Estudia con tarjetas creadas directamente a partir de tu propio material: la IA analiza el texto del documento para redactar las preguntas y respuestas.",
    benefits: [
      { title: "Tarjetas de tu propia fuente", description: "Las preguntas y respuestas se redactan a partir del documento que subes, así repasas justo el material que necesitas saber, no un mazo genérico." },
      { title: "Recuerdo activo, no relectura", description: "Cada tarjeta oculta la respuesta hasta que la giras, lo que te obliga a recuperarla de memoria: el método de estudio que de verdad funciona." },
      { title: "Elige cuántas crear", description: "Pide 5, 10, 15 o 20 tarjetas según sea un repaso rápido o un capítulo completo, generadas del mismo texto en una sola pasada." },
    ],
    workflowTitle: "Cómo encajan las tarjetas en tu estudio",
    workflowDescription: "Cuando tienes un capítulo, apuntes de clase o un manual y quieres ponerte a prueba en lugar de solo volver a leerlo.",
    steps: [
      "Sube el PDF con el que quieres estudiar.",
      "Elige cuántas tarjetas quieres y la IA redacta pares de pregunta y respuesta a partir del texto.",
      "Gira cada tarjeta para examinarte y revisa rápidamente las respuestas antes de fiarte de ellas.",
    ],
    readingTitle: "Más formas de trabajar con tu documento",
    readingDescription: "Herramientas de IA relacionadas para estudiar y entender el mismo material.",
    readingLinks: [
      { label: "Resumir un PDF", href: "/ai-summary", description: "Condensa el capítulo en puntos clave antes de convertirlo en tarjetas." },
      { label: "Chatear con un PDF", href: "/chat-with-pdf", description: "Haz preguntas de seguimiento sobre lo que las tarjetas no cubran." },
      { label: "Recursos de flujos de trabajo de documentos", href: "/resources", description: "Un centro estructurado de herramientas de documentos, conversión y rutas de estudio con IA." },
    ],
  },
  pt: {
    benefitsTitle: "Por que transformar um documento em flashcards",
    benefitsDescription: "Estude com cartões criados diretamente a partir do seu próprio material: a IA analisa o texto do documento para redigir as perguntas e respostas.",
    benefits: [
      { title: "Cartões da sua própria fonte", description: "As perguntas e respostas são redigidas a partir do documento que você envia, então você revisa exatamente o conteúdo que precisa saber, não um baralho genérico." },
      { title: "Recordação ativa, não releitura", description: "Cada cartão esconde a resposta até você virá-lo, forçando você a recuperá-la da memória: o método de estudo que realmente fixa." },
      { title: "Escolha quantos criar", description: "Peça 5, 10, 15 ou 20 cartões para uma revisão rápida ou um capítulo inteiro, gerados do mesmo texto de uma só vez." },
    ],
    workflowTitle: "Como os flashcards se encaixam no seu estudo",
    workflowDescription: "Quando você tem um capítulo, notas de aula ou um manual e quer se testar em vez de apenas reler.",
    steps: [
      "Envie o PDF com o qual você quer estudar.",
      "Escolha quantos cartões deseja e a IA redige pares de pergunta e resposta a partir do texto.",
      "Vire cada cartão para se testar e confira rapidamente as respostas antes de confiar nelas.",
    ],
    readingTitle: "Mais formas de trabalhar com seu documento",
    readingDescription: "Ferramentas de IA relacionadas para estudar e entender o mesmo material.",
    readingLinks: [
      { label: "Resumir um PDF", href: "/ai-summary", description: "Condense o capítulo em pontos-chave antes de transformá-lo em cartões." },
      { label: "Conversar com um PDF", href: "/chat-with-pdf", description: "Faça perguntas de acompanhamento sobre o que os cartões não cobrirem." },
      { label: "Recursos de fluxos de trabalho de documentos", href: "/resources", description: "Um hub estruturado de ferramentas de documentos, conversão e trilhas de estudo com IA." },
    ],
  },
  fr: {
    benefitsTitle: "Pourquoi transformer un document en fiches de révision",
    benefitsDescription: "Révisez à partir de fiches créées directement depuis votre propre matière : l'IA analyse le texte du document pour rédiger les questions et les réponses.",
    benefits: [
      { title: "Des fiches issues de votre source", description: "Les questions et réponses sont rédigées à partir du document que vous importez : vous révisez exactement la matière à connaître, pas un jeu de fiches générique." },
      { title: "Rappel actif, pas relecture", description: "Chaque fiche masque la réponse jusqu'à ce que vous la retourniez, vous obligeant à la retrouver de mémoire : la méthode de révision qui ancre vraiment." },
      { title: "Choisissez combien en créer", description: "Demandez 5, 10, 15 ou 20 fiches selon une révision rapide ou un chapitre entier, générées du même texte en une seule fois." },
    ],
    workflowTitle: "Comment les fiches s'intègrent à vos révisions",
    workflowDescription: "Quand vous avez un chapitre, des notes de cours ou un guide et que vous voulez vous tester plutôt que simplement le relire.",
    steps: [
      "Importez le PDF avec lequel vous voulez réviser.",
      "Choisissez le nombre de fiches souhaité et l'IA rédige des paires question-réponse à partir du texte.",
      "Retournez chaque fiche pour vous interroger, et vérifiez rapidement les réponses avant de vous y fier.",
    ],
    readingTitle: "D'autres façons d'exploiter votre document",
    readingDescription: "Outils d'IA associés pour réviser et comprendre la même matière.",
    readingLinks: [
      { label: "Résumer un PDF", href: "/ai-summary", description: "Condensez le chapitre en points clés avant d'en faire des fiches." },
      { label: "Discuter avec un PDF", href: "/chat-with-pdf", description: "Posez des questions de suivi sur ce que les fiches ne couvrent pas." },
      { label: "Ressources de flux de travail documentaire", href: "/resources", description: "Un hub structuré d'outils documentaires, de conversion et de parcours de révision IA." },
    ],
  },
  ja: {
    benefitsTitle: "文書をフラッシュカードにする理由",
    benefitsDescription: "自分の資料から直接作ったカードで学習——AI が文書のテキストを分析して問題と回答を作成します。",
    benefits: [
      { title: "自分の資料から作るカード", description: "問題と回答はアップロードした文書をもとに作られるので、汎用デッキではなく、覚えるべき内容そのものを復習できます。" },
      { title: "再読ではなく能動的想起", description: "各カードは裏返すまで答えを隠すため、記憶から引き出すことを促します——本当に身につく学習法です。" },
      { title: "枚数を選べる", description: "サッと復習なら少なめ、章まるごとなら多めに、5・10・15・20 枚から選べます。同じテキストから一度に生成します。" },
    ],
    workflowTitle: "フラッシュカードが学習にどう役立つか",
    workflowDescription: "章・講義ノート・マニュアルがあり、ただ読み返すのではなく自己テストしたいときに。",
    steps: [
      "学習に使いたい PDF をアップロードします。",
      "枚数を選ぶと、AI がテキストから問題と回答のペアを作成します。",
      "各カードを裏返して自己テストし、頼る前に答えを軽く確認します。",
    ],
    readingTitle: "文書を活用する他の方法",
    readingDescription: "同じ資料を学び理解するための関連 AI ツール。",
    readingLinks: [
      { label: "PDF を要約", href: "/ai-summary", description: "カードにする前に、章を要点へとまとめます。" },
      { label: "PDF とチャット", href: "/chat-with-pdf", description: "カードでカバーしきれない点を文書に追加で質問できます。" },
      { label: "文書ワークフローのリソース", href: "/resources", description: "文書ツール、変換、AI 学習の導線を整理したハブ。" },
    ],
  },
  de: {
    benefitsTitle: "Warum ein Dokument in Lernkarten verwandeln",
    benefitsDescription: "Lernen Sie mit Karten, die direkt aus Ihrem eigenen Material erstellt werden — die KI analysiert den Text des Dokuments, um die Fragen und Antworten zu formulieren.",
    benefits: [
      { title: "Karten aus Ihrer eigenen Quelle", description: "Fragen und Antworten werden aus dem Dokument geschrieben, das Sie hochladen, sodass Sie genau den Stoff wiederholen, den Sie beherrschen müssen — kein generisches Kartenset." },
      { title: "Aktives Abrufen statt erneutem Lesen", description: "Jede Karte verbirgt die Antwort, bis Sie sie umdrehen, und zwingt Sie so, sie aus dem Gedächtnis abzurufen — die Lernmethode, die wirklich haften bleibt." },
      { title: "Wählen Sie, wie viele Sie erstellen", description: "Fordern Sie 5, 10, 15 oder 20 Karten an – passend für eine kurze Wiederholung oder ein ganzes Kapitel, in einem Durchgang aus demselben Text generiert." },
    ],
    workflowTitle: "Wie Lernkarten in Ihr Lernen passen",
    workflowDescription: "Wenn Sie ein Kapitel, Vorlesungsnotizen oder ein Handbuch haben und sich selbst abfragen möchten, statt es nur erneut zu lesen.",
    steps: [
      "Laden Sie das PDF hoch, mit dem Sie lernen möchten.",
      "Wählen Sie, wie viele Karten Sie möchten, und die KI entwirft Frage-Antwort-Paare aus dem Text.",
      "Drehen Sie jede Karte um, um sich abzufragen, und prüfen Sie die Antworten kurz, bevor Sie sich auf sie verlassen.",
    ],
    readingTitle: "Weitere Wege, mit Ihrem Dokument zu arbeiten",
    readingDescription: "Verwandte KI-Tools zum Lernen und Verstehen desselben Stoffs.",
    readingLinks: [
      { label: "Ein PDF zusammenfassen", href: "/ai-summary", description: "Verdichten Sie das Kapitel zu Kernpunkten, bevor Sie es in Karten verwandeln." },
      { label: "Mit einem PDF chatten", href: "/chat-with-pdf", description: "Stellen Sie Folgefragen zu allem im Dokument, was die Karten nicht abdecken." },
      { label: "Ressourcen für Dokumenten-Workflows", href: "/resources", description: "Ein strukturierter Hub für Dokumenten-Tools, Konvertierung und KI-Lernpfade." },
    ],
  },
  ko: {
    benefitsTitle: "문서를 플래시카드로 만드는 이유",
    benefitsDescription: "당신의 자료에서 바로 만든 카드로 학습하세요 — AI가 문서의 텍스트를 분석해 문제와 답을 작성합니다.",
    benefits: [
      { title: "당신의 자료에서 만든 카드", description: "문제와 답은 업로드한 문서를 바탕으로 작성되므로, 일반적인 카드 묶음이 아니라 꼭 알아야 할 바로 그 내용을 복습합니다." },
      { title: "다시 읽기가 아닌 능동적 회상", description: "각 카드는 뒤집기 전까지 답을 숨겨, 기억에서 끄집어내도록 합니다 — 실제로 오래 남는 학습법입니다." },
      { title: "만들 개수를 선택", description: "빠른 복습부터 한 단원 전체까지, 5·10·15·20장 중에서 골라 같은 텍스트에서 한 번에 생성합니다." },
    ],
    workflowTitle: "플래시카드가 학습에 어떻게 맞물리나요",
    workflowDescription: "단원, 강의 노트, 매뉴얼을 그저 다시 읽는 대신 스스로 시험해 보고 싶을 때를 위한 기능입니다.",
    steps: [
      "학습에 쓸 PDF를 업로드하세요.",
      "원하는 카드 수를 고르면 AI가 텍스트에서 문제와 답 쌍을 작성합니다.",
      "각 카드를 뒤집어 스스로 시험하고, 답에 의존하기 전에 한 번 빠르게 확인하세요.",
    ],
    readingTitle: "문서를 활용하는 더 많은 방법",
    readingDescription: "같은 자료를 학습하고 이해하기 위한 관련 AI 도구입니다.",
    readingLinks: [
      { label: "PDF 요약", href: "/ai-summary", description: "카드로 만들기 전에 단원을 핵심 요점으로 간추립니다." },
      { label: "PDF와 대화", href: "/chat-with-pdf", description: "카드가 다루지 못한 부분을 문서에 이어서 질문하세요." },
      { label: "문서 워크플로 자료", href: "/resources", description: "문서 도구, 변환, AI 학습 경로를 정리한 구조화된 허브입니다." },
    ],
  },
};

export function QuizClient({ locale = "en", embedded = false }: { locale?: Locale; embedded?: boolean }) {
  // ko is fully authored (STR/SECTIONS carry Korean). zh-Hant derives from zh via deepHant.
  const al: AuthoredLocale = locale === "zh-Hant" ? "en" : locale;
  // childLocale collapses ONLY ko (preserves zh-Hant) for child props/runtime fns lacking "ko".
  const childLocale = locale;
  const t = locale === "zh-Hant" ? deepHant(STR.zh) : STR[al];
  const sec: ToolSectionsContent = locale === "zh-Hant" ? deepHant(SECTIONS.zh) : SECTIONS[al];
  const [fileName, setFileName] = useState("");
  const [text, setText] = useState("");
  const [count, setCount] = useState(10);
  const [phase, setPhase] = useState<"idle" | "reading" | "ready" | "generating" | "done">("idle");
  const [cards, setCards] = useState<Card[]>([]);
  const [flipped, setFlipped] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);
  const [limitHit, setLimitHit] = useState<number | null>(null);

  const onFile = useCallback(async (file: File) => {
    if (!file || (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf"))) return;
    setError(null); setCards([]); setFlipped(new Set()); setFileName(file.name); setPhase("reading");
    try {
      const pdfjs = await import("pdfjs-dist");
      pdfjs.GlobalWorkerOptions.workerSrc = "/pdf.worker.min.mjs";
      const doc = await pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise;
      let out = "";
      for (let i = 1; i <= doc.numPages; i++) {
        const page = await doc.getPage(i);
        const content = await page.getTextContent();
        out += content.items.map((it) => ("str" in it ? it.str : "")).join(" ") + "\n";
      }
      try { doc.destroy(); } catch { /* ignore */ }
      const trimmed = out.replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim();
      if (!trimmed) { setError(t.noText); setPhase("idle"); return; }
      setText(trimmed); setPhase("ready");
    } catch (e) {
      setError(encryptedPdfMessage(e, childLocale) ?? (t.err + (e instanceof Error ? e.message : String(e)))); setPhase("idle");
    }
  }, [t, childLocale]);

  const generate = useCallback(async () => {
    if (!text) return;
    const gate = await checkUsage("summary");
    if (!gate.allowed) { setLimitHit(gate.limit); return; }
    setPhase("generating"); setError(null); setCards([]); setFlipped(new Set()); setLimitHit(null);
    try {
      const auth = await authHeader();
      const res = await fetch("/api/quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...auth },
        body: JSON.stringify({ text, count, locale }),
      });
      const data = await res.json();
      if (res.status === 402 || data?.code === "UPGRADE_REQUIRED") {
        setLimitHit(data?.limit ?? gate.limit); setPhase("ready"); return;
      }
      if (data?.ok && Array.isArray(data.cards) && data.cards.length > 0) {
        setCards(data.cards);
        setPhase("done");
        trackToolRun("flashcards");
        await markUsage(gate, "summary");
      } else {
        setError(t.err + (data?.message || "Could not generate cards.")); setPhase("ready");
      }
    } catch (e) {
      setError(t.err + (e instanceof Error ? e.message : String(e))); setPhase("ready");
    }
  }, [text, count, locale, t]);

  const reset = () => { setFileName(""); setText(""); setCards([]); setFlipped(new Set()); setPhase("idle"); setError(null); setLimitHit(null); };
  const toggle = (i: number) => setFlipped((p) => { const n = new Set(p); if (n.has(i)) n.delete(i); else n.add(i); return n; });

  return (
    <div className={embedded ? "mx-auto w-full max-w-3xl px-8 pb-10 pt-4" : "mx-auto max-w-5xl px-5 pt-12 pb-16 sm:px-6 sm:pt-16 sm:pb-20"}>
      {!embedded && (
        <>
          <h1 className="text-[30px] font-normal leading-[1.1] tracking-[-0.025em] text-[color:var(--foreground)] sm:text-[40px]">{t.title}</h1>
          <p className="mt-4 text-[16px] leading-[1.6] text-[color:var(--muted)]">{t.subtitle}</p>
        </>
      )}
      {embedded && <p className="mt-4 text-[16px] leading-[1.6] text-[color:var(--muted)]">{t.subtitle}</p>}

      {phase === "idle" || phase === "reading" ? (
        <>
          <UploadDropzone locale={childLocale} buttonLabel={t.choose} busy={phase === "reading"} busyLabel={t.reading} privacy={false} note={childLocale === "zh" || childLocale === "zh-Hant" ? "本地读取 · 文字发至AI" : childLocale === "ja" ? "ローカルで読み取り · テキストをAIへ送信" : childLocale === "es" ? "Leído localmente · texto enviado a IA" : childLocale === "pt" ? "Lido localmente · texto enviado a IA" : childLocale === "fr" ? "Lu localement · texte envoyé à l'IA" : childLocale === "de" ? "Lokal gelesen · Text an KI gesendet" : childLocale === "ko" ? "로컬에서 읽기 · 텍스트 AI로 전송" : "File read locally · text sent to AI"} onFile={onFile} />
          {embedded && <WorkspaceValueZone type="ai" locale={locale} />}
        </>
      ) : (
        <>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-3">
              <p className="truncate text-[14px] font-semibold text-[color:var(--foreground)]" title={fileName}>{fileName}</p>
              <button type="button" onClick={reset} className="text-[12.5px] font-medium text-[color:var(--muted)] hover:text-[color:var(--foreground)]">{t.change}</button>
            </div>
            <div className="flex shrink-0 items-center gap-3">
              <label className="flex items-center gap-2 text-[12.5px] text-[color:var(--muted)]">
                {t.count}
                <select value={count} onChange={(e) => setCount(+e.target.value)} className="h-9 rounded-[var(--radius)] border border-[color:var(--line)] bg-[color:var(--surface-subtle)] px-2 text-[13px] text-[color:var(--foreground)]">
                  {[5, 10, 15, 20].map((n) => <option key={n} value={n}>{n}</option>)}
                </select>
              </label>
              <button type="button" onClick={generate} disabled={phase === "generating"} className="inline-flex items-center gap-2 rounded-[var(--radius)] bg-[color:var(--accent)] px-5 py-2 text-[13px] font-semibold text-white transition hover:opacity-90 disabled:opacity-50">{phase === "generating" ? (<><Spinner /> {t.generating}</>) : t.generate}</button>
            </div>
          </div>

          {phase === "done" && cards.length > 0 && (
            <>
              <p className="mt-4 text-[12px] text-[color:var(--faint)]">{t.note}</p>
              <div className="mt-3 grid gap-3 sm:grid-cols-2">
                {cards.map((c, i) => {
                  const open = flipped.has(i);
                  return (
                    <button key={i} type="button" onClick={() => toggle(i)} className="group flex min-h-[120px] flex-col rounded-[var(--radius-lg)] border border-[color:var(--line)] bg-[color:var(--surface)] p-4 text-left transition hover:border-[color:var(--accent)]">
                      <span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[color:var(--accent-strong)]">{open ? t.answer : t.question}</span>
                      <span className="mt-2 flex-1 text-[14px] leading-6 text-[color:var(--foreground)]">{open ? c.a : c.q}</span>
                      <span className="mt-2 text-[11px] text-[color:var(--faint)] opacity-0 transition group-hover:opacity-100">{t.flip}</span>
                    </button>
                  );
                })}
              </div>
            </>
          )}
        </>
      )}

      {error && <div className="mt-4 rounded-[var(--radius)] border border-[rgba(248,113,113,0.3)] bg-[rgba(248,113,113,0.08)] px-4 py-3 text-[13.5px] text-[#f87171]">{error}</div>}
      {limitHit !== null && <UpgradePrompt locale={childLocale === "ko" ? "en" : childLocale} limit={limitHit} />}
      {!embedded && <ToolSections locale={locale} content={sec} />}
      {!embedded && <ToolFaq tool="flashcards" locale={locale} />}
    </div>
  );
}
