import { deepHant } from "@/lib/zh-hant";

// ─────────────────────────────────────────────────────────────────────────────
// FOOTER NAV — single source (P2.1). The footer tool columns used to be 6 near-
// identical per-locale arrays (toolColsEn…toolColsJa). This collapses them into:
//   • footerStructure — locale-independent (which columns, which hrefs, the order)
//   • footerLabels     — one block per locale; the ONLY place a footer label lives
// Adding a locale = add one footerLabels block. zh-Hant derives from zh (deepHant).
// ENFORCEMENT is correct-by-construction (same philosophy as P0.2): footerLabels is
// a typed-exhaustive Record<AuthoredLocale, Record<FooterKey, string>>, so adding a
// locale to AuthoredLocale (e.g. "de") with a missing block — or any block missing a
// key — is a tsc error (red build), not a silent English fallback at runtime.
// (Header/Footer labels intentionally differ in places — a separate UX/brand item;
// this hoist is structure-only, zero copy change.)
// ─────────────────────────────────────────────────────────────────────────────

type AuthoredLocale = "en" | "zh" | "es" | "pt" | "fr" | "ja" | "de" | "ko";

// Column = a title key + the hrefs in order. Same across every locale. `as const`
// so FooterKey can be derived from it (single source — no second list to maintain).
export const footerStructure = [
  { titleKey: "ai", hrefs: ["/chat-with-pdf", "/ai-summary", "/flashcards", "/batch-summary", "/batch-sort", "/ocr-pdf", "/extract-to-excel", "/redline"] },
  { titleKey: "convert", hrefs: ["/word-to-pdf", "/pdf-to-word", "/excel-to-pdf", "/pdf-to-excel", "/pdf-to-ppt", "/pdf-to-pdfa", "/ppt-to-pdf", "/jpg-to-pdf", "/images-to-pdf", "/pdf-to-image", "/pdf-to-markdown", "/pdf-to-html", "/pdf-to-text", "/html-to-pdf"] },
  { titleKey: "edit", hrefs: ["/merge-pdf", "/split-pdf", "/compress-pdf", "/delete-page", "/rotate-page", "/crop-pdf", "/watermark-pdf", "/sign-pdf", "/redact-pdf", "/batch-compress", "/protect-pdf", "/unlock-pdf"] },
  { titleKey: "company", hrefs: ["/about", "/blog", "/guides", "/pricing", "/contact"] },
] as const;

// Every label key = a column titleKey or an href above. Derived from footerStructure
// so a new column/tool automatically demands a label in EVERY locale (tsc-enforced).
type FooterKey =
  | (typeof footerStructure)[number]["titleKey"]
  | (typeof footerStructure)[number]["hrefs"][number];

// Labels per locale. Keys = the column titleKeys + every href above. Translations
// are verbatim from the previous toolCols arrays (zero copy change).
export const footerLabels: Record<AuthoredLocale, Record<FooterKey, string>> = {
  en: { ai: "AI Workspace", "/chat-with-pdf": "Chat with PDF", "/ai-summary": "AI Summary", "/flashcards": "Flashcards", "/batch-summary": "Batch summary", "/batch-sort": "Auto-classify", "/ocr-pdf": "OCR Workspace", "/extract-to-excel": "Extract to Excel", "/redline": "Compare versions", convert: "Convert", "/word-to-pdf": "Word to PDF", "/pdf-to-word": "PDF to Word", "/excel-to-pdf": "Excel to PDF", "/pdf-to-excel": "PDF to Excel", "/pdf-to-ppt": "PDF to PPT", "/pdf-to-pdfa": "PDF to PDF/A", "/ppt-to-pdf": "PPT to PDF", "/jpg-to-pdf": "JPG to PDF", "/images-to-pdf": "Image to PDF", "/pdf-to-image": "PDF to Image", "/pdf-to-markdown": "PDF to Markdown", "/pdf-to-html": "PDF to HTML", "/pdf-to-text": "PDF to Text", "/html-to-pdf": "HTML to PDF", edit: "Edit & Organize", "/merge-pdf": "Merge PDF", "/split-pdf": "Split PDF", "/compress-pdf": "Compress PDF", "/delete-page": "Delete Page", "/rotate-page": "Rotate Page", "/crop-pdf": "Crop PDF", "/watermark-pdf": "Watermark PDF", "/sign-pdf": "Sign PDF", "/redact-pdf": "Redact PDF", "/batch-compress": "Batch compress", "/protect-pdf": "Protect PDF", "/unlock-pdf": "Unlock PDF", company: "Company", "/about": "About", "/blog": "Blog", "/guides": "Guides", "/pricing": "Pricing", "/contact": "Contact" },
  zh: { ai: "AI 工作区", "/chat-with-pdf": "PDF 问答", "/ai-summary": "AI 摘要", "/flashcards": "抽认卡", "/batch-summary": "批量摘要", "/batch-sort": "自动分类", "/ocr-pdf": "OCR 工作区", "/extract-to-excel": "抽取到表格", "/redline": "版本对比", convert: "转换", "/word-to-pdf": "Word 转 PDF", "/pdf-to-word": "PDF 转 Word", "/excel-to-pdf": "Excel 转 PDF", "/pdf-to-excel": "PDF 转 Excel", "/pdf-to-ppt": "PDF 转 PPT", "/pdf-to-pdfa": "PDF 转 PDF/A", "/ppt-to-pdf": "PPT 转 PDF", "/jpg-to-pdf": "JPG 转 PDF", "/images-to-pdf": "图片转 PDF", "/pdf-to-image": "PDF 转图片", "/pdf-to-markdown": "PDF 转 Markdown", "/pdf-to-html": "PDF 转 HTML", "/pdf-to-text": "PDF 转文本", "/html-to-pdf": "HTML 转 PDF", edit: "编辑与整理", "/merge-pdf": "合并 PDF", "/split-pdf": "拆分 PDF", "/compress-pdf": "压缩 PDF", "/delete-page": "删除页面", "/rotate-page": "旋转页面", "/crop-pdf": "裁剪 PDF", "/watermark-pdf": "PDF 水印", "/sign-pdf": "PDF 签名", "/redact-pdf": "PDF 脱敏", "/batch-compress": "批量压缩", "/protect-pdf": "加密 PDF", "/unlock-pdf": "解密 PDF", company: "公司", "/about": "关于", "/blog": "博客", "/guides": "指南", "/pricing": "定价", "/contact": "联系" },
  es: { ai: "Espacio de trabajo IA", "/chat-with-pdf": "Chat con PDF", "/ai-summary": "Resumen IA", "/flashcards": "Tarjetas", "/batch-summary": "Resumen por lotes", "/batch-sort": "Clasificar", "/ocr-pdf": "Espacio OCR", "/extract-to-excel": "Extraer a Excel", "/redline": "Comparar versiones", convert: "Convertir", "/word-to-pdf": "Word a PDF", "/pdf-to-word": "PDF a Word", "/excel-to-pdf": "Excel a PDF", "/pdf-to-excel": "PDF a Excel", "/pdf-to-ppt": "PDF a PPT", "/pdf-to-pdfa": "PDF a PDF/A", "/ppt-to-pdf": "PPT a PDF", "/jpg-to-pdf": "JPG a PDF", "/images-to-pdf": "Imagen a PDF", "/pdf-to-image": "PDF a imagen", "/pdf-to-markdown": "PDF a Markdown", "/pdf-to-html": "PDF a HTML", "/pdf-to-text": "PDF a Texto", "/html-to-pdf": "HTML a PDF", edit: "Editar y organizar", "/merge-pdf": "Unir PDF", "/split-pdf": "Dividir PDF", "/compress-pdf": "Comprimir PDF", "/delete-page": "Eliminar página", "/rotate-page": "Rotar página", "/crop-pdf": "Recortar PDF", "/watermark-pdf": "Marca de agua", "/sign-pdf": "Firmar PDF", "/redact-pdf": "Censurar PDF", "/batch-compress": "Compresión por lotes", "/protect-pdf": "Proteger PDF", "/unlock-pdf": "Desbloquear PDF", company: "Empresa", "/about": "Acerca de", "/blog": "Blog", "/guides": "Guías", "/pricing": "Precios", "/contact": "Contacto" },
  pt: { ai: "Espaço de trabalho IA", "/chat-with-pdf": "Chat com PDF", "/ai-summary": "Resumo IA", "/flashcards": "Flashcards", "/batch-summary": "Resumo em lote", "/batch-sort": "Classificar", "/ocr-pdf": "Espaço OCR", "/extract-to-excel": "Extrair para Excel", "/redline": "Comparar versões", convert: "Converter", "/word-to-pdf": "Word para PDF", "/pdf-to-word": "PDF para Word", "/excel-to-pdf": "Excel para PDF", "/pdf-to-excel": "PDF para Excel", "/pdf-to-ppt": "PDF para PPT", "/pdf-to-pdfa": "PDF para PDF/A", "/ppt-to-pdf": "PPT para PDF", "/jpg-to-pdf": "JPG para PDF", "/images-to-pdf": "Imagem para PDF", "/pdf-to-image": "PDF para imagem", "/pdf-to-markdown": "PDF para Markdown", "/pdf-to-html": "PDF para HTML", "/pdf-to-text": "PDF para Texto", "/html-to-pdf": "HTML para PDF", edit: "Editar e organizar", "/merge-pdf": "Unir PDF", "/split-pdf": "Dividir PDF", "/compress-pdf": "Comprimir PDF", "/delete-page": "Excluir página", "/rotate-page": "Girar página", "/crop-pdf": "Recortar PDF", "/watermark-pdf": "Marca d'água", "/sign-pdf": "Assinar PDF", "/redact-pdf": "Redigir PDF", "/batch-compress": "Compressão em lote", "/protect-pdf": "Proteger PDF", "/unlock-pdf": "Desbloquear PDF", company: "Empresa", "/about": "Sobre", "/blog": "Blog", "/guides": "Guias", "/pricing": "Preços", "/contact": "Contato" },
  fr: { ai: "Espace de travail IA", "/chat-with-pdf": "Chat avec PDF", "/ai-summary": "Résumé IA", "/flashcards": "Flashcards", "/batch-summary": "Résumé par lots", "/batch-sort": "Classifier", "/ocr-pdf": "Espace OCR", "/extract-to-excel": "Extraire vers Excel", "/redline": "Comparer versions", convert: "Convertir", "/word-to-pdf": "Word en PDF", "/pdf-to-word": "PDF en Word", "/excel-to-pdf": "Excel en PDF", "/pdf-to-excel": "PDF en Excel", "/pdf-to-ppt": "PDF en PPT", "/pdf-to-pdfa": "PDF en PDF/A", "/ppt-to-pdf": "PPT en PDF", "/jpg-to-pdf": "JPG en PDF", "/images-to-pdf": "Image en PDF", "/pdf-to-image": "PDF en image", "/pdf-to-markdown": "PDF en Markdown", "/pdf-to-html": "PDF en HTML", "/pdf-to-text": "PDF en Texte", "/html-to-pdf": "HTML en PDF", edit: "Éditer et organiser", "/merge-pdf": "Fusionner PDF", "/split-pdf": "Diviser PDF", "/compress-pdf": "Compresser PDF", "/delete-page": "Supprimer une page", "/rotate-page": "Faire pivoter", "/crop-pdf": "Rogner PDF", "/watermark-pdf": "Filigrane", "/sign-pdf": "Signer PDF", "/redact-pdf": "Caviarder PDF", "/batch-compress": "Compression par lots", "/protect-pdf": "Protéger PDF", "/unlock-pdf": "Déverrouiller PDF", company: "Entreprise", "/about": "À propos", "/blog": "Blog", "/guides": "Guides", "/pricing": "Tarifs", "/contact": "Contact" },
  ja: { ai: "AI ワークスペース", "/chat-with-pdf": "PDFと対話", "/ai-summary": "AI要約", "/flashcards": "フラッシュカード", "/batch-summary": "一括要約", "/batch-sort": "自動分類", "/ocr-pdf": "OCRワークスペース", "/extract-to-excel": "Excelに抽出", "/redline": "バージョン比較", convert: "変換", "/word-to-pdf": "WordをPDFに変換", "/pdf-to-word": "PDFをWordに変換", "/excel-to-pdf": "ExcelをPDFに変換", "/pdf-to-excel": "PDFをExcelに変換", "/pdf-to-ppt": "PDFをPPTに変換", "/pdf-to-pdfa": "PDFをPDF/Aに変換", "/ppt-to-pdf": "PPTをPDFに変換", "/jpg-to-pdf": "JPGをPDFに変換", "/images-to-pdf": "画像をPDFに変換", "/pdf-to-image": "PDFを画像に変換", "/pdf-to-markdown": "PDFをMarkdownに変換", "/pdf-to-html": "PDFをHTMLに変換", "/pdf-to-text": "PDFをテキストに変換", "/html-to-pdf": "HTMLをPDFに変換", edit: "編集・整理", "/merge-pdf": "PDFを結合", "/split-pdf": "PDFを分割", "/compress-pdf": "PDFを圧縮", "/delete-page": "ページを削除", "/rotate-page": "ページを回転", "/crop-pdf": "PDFをトリミング", "/watermark-pdf": "PDFに透かし", "/sign-pdf": "PDFに署名", "/redact-pdf": "PDFを墨消し", "/batch-compress": "一括圧縮", "/protect-pdf": "PDFを保護", "/unlock-pdf": "PDFのロック解除", company: "会社", "/about": "会社概要", "/blog": "ブログ", "/guides": "ガイド", "/pricing": "料金", "/contact": "お問い合わせ" },
  de: { ai: "KI-Arbeitsbereich", "/chat-with-pdf": "Mit PDF chatten", "/ai-summary": "KI-Zusammenfassung", "/flashcards": "Lernkarten", "/batch-summary": "Stapel-Zusammenfassung", "/batch-sort": "Automatisch klassifizieren", "/ocr-pdf": "OCR-Arbeitsbereich", "/extract-to-excel": "In Excel extrahieren", "/redline": "Versionen vergleichen", convert: "Konvertieren", "/word-to-pdf": "Word in PDF", "/pdf-to-word": "PDF in Word", "/excel-to-pdf": "Excel in PDF", "/pdf-to-excel": "PDF in Excel", "/pdf-to-ppt": "PDF in PPT", "/pdf-to-pdfa": "PDF in PDF/A", "/ppt-to-pdf": "PPT in PDF", "/jpg-to-pdf": "JPG in PDF", "/images-to-pdf": "Bild in PDF", "/pdf-to-image": "PDF in Bild", "/pdf-to-markdown": "PDF in Markdown", "/pdf-to-html": "PDF in HTML", "/pdf-to-text": "PDF in Text", "/html-to-pdf": "HTML in PDF", edit: "Bearbeiten & Ordnen", "/merge-pdf": "PDF zusammenfügen", "/split-pdf": "PDF teilen", "/compress-pdf": "PDF komprimieren", "/delete-page": "Seiten löschen", "/rotate-page": "Seiten drehen", "/crop-pdf": "PDF zuschneiden", "/watermark-pdf": "Wasserzeichen-PDF", "/sign-pdf": "PDF unterschreiben", "/redact-pdf": "PDF schwärzen", "/batch-compress": "Komprimieren (Stapel)", "/protect-pdf": "PDF schützen", "/unlock-pdf": "PDF entsperren", company: "Unternehmen", "/about": "Über uns", "/blog": "Blog", "/guides": "Anleitungen", "/pricing": "Preise", "/contact": "Kontakt" },
  ko: { ai: "AI 워크스페이스", "/chat-with-pdf": "PDF와 대화", "/ai-summary": "AI 요약", "/flashcards": "플래시카드", "/batch-summary": "일괄 요약", "/batch-sort": "자동 분류", "/ocr-pdf": "OCR 워크스페이스", "/extract-to-excel": "Excel로 추출", "/redline": "버전 비교", convert: "변환", "/word-to-pdf": "Word를 PDF로", "/pdf-to-word": "PDF를 Word로", "/excel-to-pdf": "Excel을 PDF로", "/pdf-to-excel": "PDF를 Excel로", "/pdf-to-ppt": "PDF를 PPT로", "/pdf-to-pdfa": "PDF를 PDF/A로", "/ppt-to-pdf": "PPT를 PDF로", "/jpg-to-pdf": "JPG를 PDF로", "/images-to-pdf": "이미지를 PDF로", "/pdf-to-image": "PDF를 이미지로", "/pdf-to-markdown": "PDF를 Markdown으로", "/pdf-to-html": "PDF를 HTML로", "/pdf-to-text": "PDF를 텍스트로", "/html-to-pdf": "HTML을 PDF로", edit: "편집 및 정리", "/merge-pdf": "PDF 병합", "/split-pdf": "PDF 분할", "/compress-pdf": "PDF 압축", "/delete-page": "페이지 삭제", "/rotate-page": "페이지 회전", "/crop-pdf": "PDF 자르기", "/watermark-pdf": "PDF 워터마크", "/sign-pdf": "PDF 서명", "/redact-pdf": "PDF 텍스트 지우기", "/batch-compress": "일괄 압축", "/protect-pdf": "PDF 암호화", "/unlock-pdf": "PDF 잠금 해제", company: "회사", "/about": "회사 소개", "/blog": "블로그", "/guides": "가이드", "/pricing": "요금제", "/contact": "문의하기" },
};

export type FooterCol = { title: string; links: { label: string; href: string }[] };

// Derive the rendered columns for a locale. zh-Hant = deepHant(zh); any unknown
// locale falls back to en. Per-key en fallback guards against a missing label.
export function getFooterCols(locale: string): FooterCol[] {
  const labels =
    locale === "zh-Hant"
      ? (deepHant(footerLabels.zh) as Record<string, string>)
      : (footerLabels[locale as AuthoredLocale] ?? footerLabels.en);
  return footerStructure.map((col) => ({
    title: labels[col.titleKey] ?? footerLabels.en[col.titleKey],
    links: col.hrefs.map((href) => ({ label: labels[href] ?? footerLabels.en[href], href })),
  }));
}
