// Auto-generated by apps/dockdocs/scripts/parse-project-board.mjs.
// PMO Board is the source of truth for Mission Control task status.

export const projectBoardGenerated = {
  "generatedAt": "2026-06-04T04:15:58.873Z",
  "source": "pmo-board",
  "syncStatus": "PMO同步正常",
  "activeTasks": [
    "None"
  ],
  "blockedTasks": [
    "None confirmed"
  ],
  "completedTasks": [
    "DEV-100 (DEV)",
    "DEV-200 (DEV)",
    "DEV-300 AI Workspace Premium Phase 1 (DEV)",
    "DEV-301 Production Pro Session QA (DEV)",
    "OPS-010 (OPS)",
    "OPS-011 (OPS)",
    "OPS-100 Mission Control Phase 1 (OPS)",
    "OPS-102 Codex Task Queue Runner (OPS)",
    "OPS-102A Hardened Task Queue Runner (OPS)",
    "OPS-103 Mission Control x Task Queue (OPS)",
    "OPS-104A Project Inventory (OPS)"
  ],
  "productionStatus": [
    "Mission Control: Deployed to production",
    "Production URL: https://dockdocs.app/internal/mission-control/",
    "Latest production deploy includes: OPS-100, OPS-102, OPS-102A, OPS-103, OPS-104A, DEV-300",
    "PMO Direction: Keep Mission Control as single source of truth."
  ],
  "nextRecommended": [
    "Keep Mission Control as the single source of truth.",
    "Start the next PMO-approved production task."
  ],
  "lanes": {
    "DEV": {
      "Backlog": [],
      "In Progress": [],
      "QA": [],
      "Merged": [],
      "Production": [
        "DEV-100",
        "DEV-200",
        "DEV-300"
      ]
    },
    "UI": {
      "Backlog": [],
      "In Progress": [],
      "QA": [],
      "Merged": [],
      "Production": []
    },
    "OPS": {
      "Backlog": [],
      "In Progress": [],
      "QA": [],
      "Merged": [],
      "Production": [
        "OPS-010",
        "OPS-011",
        "OPS-100",
        "OPS-102",
        "OPS-102A",
        "OPS-103",
        "OPS-104A"
      ]
    },
    "SEO": {
      "Backlog": [],
      "In Progress": [],
      "QA": [],
      "Merged": [],
      "Production": []
    },
    "GEO": {
      "Backlog": [],
      "In Progress": [],
      "QA": [],
      "Merged": [],
      "Production": []
    }
  },
  "tasks": [
    {
      "id": "DEV-100",
      "label": "Commercialization MVP",
      "area": "DEV",
      "status": "Production"
    },
    {
      "id": "DEV-200",
      "label": "Billing MVP",
      "area": "DEV",
      "status": "Production"
    },
    {
      "id": "DEV-300",
      "label": "AI Workspace Premium Phase 1",
      "area": "DEV",
      "status": "Production"
    },
    {
      "id": "DEV-301",
      "label": "Production Pro Session QA",
      "area": "DEV",
      "status": "Completed"
    },
    {
      "id": "UI-301A",
      "label": "中文内部项目驾驶舱",
      "area": "UI",
      "status": "Completed"
    },
    {
      "id": "OPS-010",
      "label": "Google OAuth enablement follow-up",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-011",
      "label": "Production login validation follow-up",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-100",
      "label": "Mission Control Phase 1",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-102",
      "label": "Codex Task Queue Runner",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-102A",
      "label": "Hardened Task Queue Runner",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-103",
      "label": "Mission Control x Task Queue",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-104A",
      "label": "Project Inventory",
      "area": "OPS",
      "status": "Production"
    },
    {
      "id": "OPS-106",
      "label": "Mission Control Auto Sync",
      "area": "OPS",
      "status": "Completed"
    }
  ],
  "warnings": [
    "UI-301A is missing from the PMO board; using current release fallback.",
    "OPS-106 is missing from the PMO board; using current release fallback."
  ]
} as const;
